package com.sap.sse.gwt.client.shared.settings;

import com.google.gwt.json.client.JSONObject;
import com.google.gwt.json.client.JSONParser;

/**
 * Represents a generic representation of settings. Its used as a layer between
 * {@link com.sap.sse.common.settings.Settings Settings} object and persistence layer.
 * 
 * @author Vladislav Chumak
 *
 */
public class StorableSettingsRepresentation {

    private final JSONObject internalSettingsRepresentation;

    /**
     * 
     * @param settingsJsonRepresentation
     *            The representation of settings generated by using {@link #asJson()}. May not
     *            be {@code null}.
     */
    public StorableSettingsRepresentation(JSONObject settingsJsonRepresentation) {
        this.internalSettingsRepresentation = settingsJsonRepresentation;
    }

    /**
     * 
     * @param settingsStringRepresentation
     *            The representation of settings generated by using {@link #asString()}. May
     *            not be {@code null}.
     */
    public StorableSettingsRepresentation(String settingsStringRepresentation) {
        this.internalSettingsRepresentation = (JSONObject) JSONParser.parseLenient(settingsStringRepresentation);
    }

    /**
     * 
     * @return The representation of settings as JSON. Cannot be {@code null}.
     */
    public JSONObject asJson() {
        return internalSettingsRepresentation;
    }

    /**
     * 
     * @return The representation of settings as String. Cannot be {@code null}.
     */
    public String asString() {
        return internalSettingsRepresentation.toString();
    }

}
