package com.sap.sailing.domain.persistence.impl;

public enum FieldNames {
    // general:
    TIME_AS_MILLIS, KNOT_SPEED, DEGREE_BEARING, LAT_DEG, LNG_DEG,
    
    FLEET, RACE_IDENTIFIERS,
    
    /**
     * TODO this will have to be renamed to REGATTA_NAME, but compatibility concerns keep us from doing so at the moment
     */
    EVENT_NAME,
    EVENT_PUBLICATION_URL,
    EVENT_IS_PUBLIC,
    
    REGATTA_NAME,
    REGATTA_BASE_NAME,
    REGATTA_SERIES,
    SERIES_NAME,
    SERIES_IS_MEDAL,
    SERIES_FLEETS,
    SERIES_RACE_COLUMNS,
    FLEET_NAME,
    FLEET_ORDERING,
    FLEET_COLOR,
    
    SCORING_SCHEME_TYPE,
    
    RACE_NAME,
    
    VENUE,
    VENUE_NAME,
    
    COURSE_AREAS,
    COURSE_AREA_NAME,
    
    BOAT_CLASS_NAME,
    BOAT_CLASS_TYPICALLY_STARTS_UPWIND,
    
    // wind:
    WIND_SOURCE_NAME, WIND_SOURCE_ID, WIND,
    
    // SwissTiming configuration parameters:
    ST_CONFIG_NAME, ST_CONFIG_HOSTNAME, ST_CONFIG_PORT,

    // leaderboard:
    LEADERBOARD_NAME, LEADERBOARD_SUPPRESSED_COMPETITORS, LEADERBOARD_COLUMNS, LEADERBOARD_COLUMN_NAME, LEADERBOARD_COMPETITOR_DISPLAY_NAMES,
    LEADERBOARD_IS_MEDAL_RACE_COLUMN, LEADERBOARD_CARRIED_POINTS, LEADERBOARD_SCORE_CORRECTIONS, LEADERBOARD_DISCARDING_THRESHOLDS,
    LEADERBOARD_SCORE_CORRECTION_MAX_POINTS_REASON, LEADERBOARD_CORRECTED_SCORE, LEADERBOARD_SCORE_CORRECTION_TIMESTAMP,
    LEADERBOARD_SCORE_CORRECTION_COMMENT, LEADERBOARD_COLUMN_FACTORS,

    // leaderboard group
    LEADERBOARD_GROUP_NAME, LEADERBOARD_GROUP_DESCRIPTION, LEADERBOARD_GROUP_LEADERBOARDS, LEADERBOARD_GROUP_OVERALL_LEADERBOARD,
    LEADERBOARD_GROUP_DISPLAY_IN_REVERSE_ORDER,
    
    // race ID to regatta name
    RACE_ID_AS_STRING,
    
    // race committee
    RC_EVENT, RC_EVENT_PASS_ID, RC_EVENT_ID, RC_EVENT_INVOLVED_BOATS, RC_EVENT_FLAG_UPPER, RC_EVENT_FLAG_LOWER, RC_EVENT_FLAG_DISPLAYED, 
    RC_EVENT_START_TIME, RC_EVENT_CLASS;
}
