package com.sap.sailing.domain.persistence.impl;

public enum FieldNames {
    // general:
    TIME_AS_MILLIS, KNOT_SPEED, DEGREE_BEARING, LAT_DEG, LNG_DEG,
    
    FLEET, RACE_IDENTIFIERS,
    
    /**
     * TODO this will have to be renamed to REGATTA_NAME, but compatibility concerns keep us from doing so at the moment
     */
    EVENT_NAME,
    EVENT_DESCRIPTION,
    EVENT_ID,
    EVENT_IS_PUBLIC,
    EVENT_START_DATE,
    EVENT_END_DATE,
    EVENT_IMAGE_URLS,
    EVENT_VIDEO_URLS,
    EVENT_SPONSOR_IMAGE_URLS,
    EVENT_OFFICIAL_WEBSITE_URL,
    EVENT_LOGO_IMAGE_URL,
    
    REGATTA_NAME,
    REGATTA_ID,
    REGATTA_BASE_NAME,
    REGATTA_START_DATE,
    REGATTA_END_DATE,
    REGATTA_SERIES,
    REGATTA_REGATTA_CONFIGURATION,
    REGATTA_USE_START_TIME_INFERENCE,
    SERIES_NAME,
    SERIES_IS_MEDAL,
    SERIES_STARTS_WITH_ZERO_SCORE,
    SERIES_HAS_SPLIT_FLEET_CONTIGUOUS_SCORING,
    SERIES_STARTS_WITH_NON_DISCARDABLE_CARRY_FORWARD,
    SERIES_FLEETS,
    SERIES_RACE_COLUMNS,
    SERIES_DISCARDING_THRESHOLDS,
    FLEET_NAME,
    FLEET_ORDERING,
    FLEET_COLOR,
    
    SCORING_SCHEME_TYPE,
    
    RACE_NAME,
    RACE_ID,
    
    VENUE,
    VENUE_NAME,

    COURSE_AREAS,
    COURSE_AREA_NAME,
    COURSE_AREA_ID,
    
    BOAT_CLASS_NAME,
    BOAT_CLASS_TYPICALLY_STARTS_UPWIND,
    
    // wind:
    WIND_SOURCE_NAME, WIND_SOURCE_ID, WIND,
    
    // SwissTiming configuration parameters:
    ST_CONFIG_NAME, ST_CONFIG_HOSTNAME, ST_CONFIG_PORT,

    COMPETITOR_ID, COMPETITOR_DISPLAY_NAME,
    
    // leaderboard:
    LEADERBOARD_NAME, LEADERBOARD_DISPLAY_NAME, LEADERBOARD_SUPPRESSED_COMPETITORS, LEADERBOARD_SUPPRESSED_COMPETITOR_IDS,
    LEADERBOARD_COLUMNS, LEADERBOARD_COLUMN_NAME, LEADERBOARD_COMPETITOR_DISPLAY_NAMES,
    LEADERBOARD_IS_MEDAL_RACE_COLUMN, LEADERBOARD_CARRIED_POINTS, LEADERBOARD_CARRIED_POINTS_BY_ID,
    LEADERBOARD_SCORE_CORRECTIONS, LEADERBOARD_DISCARDING_THRESHOLDS,
    LEADERBOARD_SCORE_CORRECTION_MAX_POINTS_REASON, LEADERBOARD_CORRECTED_SCORE, LEADERBOARD_SCORE_CORRECTION_TIMESTAMP,
    LEADERBOARD_SCORE_CORRECTION_COMMENT, LEADERBOARD_COLUMN_FACTORS,

    // leaderboard group
    LEADERBOARD_GROUP_UUID, LEADERBOARD_GROUP_NAME, LEADERBOARD_GROUP_DESCRIPTION,
    LEADERBOARD_GROUP_DISPLAY_NAME, LEADERBOARD_GROUP_LEADERBOARDS, LEADERBOARD_GROUP_OVERALL_LEADERBOARD,
    LEADERBOARD_GROUP_DISPLAY_IN_REVERSE_ORDER,
    
    // race ID to regatta name
    RACE_ID_AS_STRING,
    
    // race log
    RACE_LOG_IDENTIFIER, RACE_LOG_EVENT, RACE_LOG_EVENT_PASS_ID, RACE_LOG_EVENT_ID, RACE_LOG_EVENT_CREATED_AT, RACE_LOG_EVENT_AUTHOR_NAME,
    RACE_LOG_EVENT_AUTHOR_PRIORITY, RACE_LOG_EVENT_INVOLVED_BOATS, RACE_LOG_EVENT_FLAG_UPPER, RACE_LOG_EVENT_FLAG_LOWER, RACE_LOG_EVENT_FLAG_DISPLAYED,
    RACE_LOG_EVENT_START_TIME, RACE_LOG_EVENT_CLASS, RACE_LOG_EVENT_NEXT_STATUS, RACE_LOG_COURSE_DESIGN, WAYPOINT_ID, WAYPOINT_NAME,
    WAYPOINT_PASSINGINSTRUCTIONS, CONTROLPOINT, CONTROLPOINT_CLASS, MARK_ID, MARK_COLOR, MARK_NAME, MARK_PATTERN, MARK_SHAPE, MARK_TYPE,
    CONTROLPOINT_VALUE, CONTROLPOINTWITHTWOMARKS_ID, CONTROLPOINTWITHTWOMARKS_NAME, CONTROLPOINTWITHTWOMARKS_LEFT, CONTROLPOINTWITHTWOMARKS_RIGHT,
    RACE_LOG_POSITIONED_COMPETITORS, RACE_LOG_PATHFINDER_ID, RACE_LOG_GATE_LINE_OPENING_TIME, RACE_LOG_GOLF_DOWN_TIME, RACE_LOG_START_PROCEDURE_TYPE,
    RACE_LOG_PROTEST_START_TIME, RACE_LOG_COURSE_DESIGN_NAME, RACE_LOG_REVOKED_EVENT_ID, RACE_LOG_REVOKED_EVENT_TYPE, RACE_LOG_REVOKED_EVENT_SHORT_INFO,
    RACE_LOG_REVOKED_REASON, RACE_LOG_FROM, RACE_LOG_TO, RACE_LOG_MARK, RACE_LOG_DEVICE_MAPPING_EVENT_ID,
    RACE_LOG_CLOSING_TIMEPOINT, TIMEPOINT_OF_FIXED_MARKPASSING, INDEX_OF_PASSED_WAYPOINT,INDEX_OF_FIRST_SUPPRESSED_WAYPOINT, MARK,
    /** @deprecated Replaced by WAYPOINT_PASSINGINSTRUCTIONS, still used to migrate old races*/ @Deprecated WAYPOINT_PASSINGSIDE,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_ID, still used to migrate old races*/ @Deprecated GATE_ID,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_NAME, still used to migrate old races*/ @Deprecated GATE_NAME,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_LEFT, still used to migrate old races*/ @Deprecated GATE_LEFT,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_RIGHT, still used to migrate old races*/ @Deprecated GATE_RIGHT,

    // sailing server
    SERVER_NAME,
    SERVER_URL,
    
    // configurations
    CONFIGURATION_MATCHER, CONFIGURATION_CONFIG, CONFIGURATION_MATCHER_ID, CONFIGURATION_MATCHER_TYPE, CONFIGURATION_MATCHER_CLIENTS, 
    CONFIGURATION_CONFIG_ALLOWED_COURSE_AREA_NAMES, CONFIGURATION_CONFIG_MIN_ROUNDS, CONFIGURATION_CONFIG_MAX_ROUNDS, CONFIGURATION_CONFIG_RESULTS_MAIL,
    CONFIGURATION_CONFIG_PROCEDURES,
    
    // GPSFixes
    DEVICE_TYPE_SPECIFIC_ID, DEVICE_ID, DEVICE_TYPE, GPSFIX_TYPE, GPSFIX, DEVICE_STRING_REPRESENTATION,
    
    // GPSFixes metadata
    TIMERANGE, NUM_FIXES,
    
    // Timespan
    FROM_MILLIS, TO_MILLIS,

    // Result Import url fields
    RESULT_PROVIDERNAME, RESULT_URL, 
    
    // type of additional scoring information
    RACE_LOG_ADDITIONAL_SCORING_INFORMATION_TYPE
}
