package com.sap.sailing.expeditionconnector.impl;

import com.sap.sailing.domain.racelogtracking.DeviceIdentifierStringSerializationHandler;

public class ExpeditionSensorStringSerializationHandler extends ExpeditionSensorDeviceIdentifierSerializationHandler
implements DeviceIdentifierStringSerializationHandler {

}
