version = 1
SPDX-PackageName = "sailing-analytics"
SPDX-PackageSupplier = "SAP Open Source Program Office ospo@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/SAP/sailing-analytics"
SPDX-PackageComment = "The code in this project may include calls to APIs (\"API Calls\") of\n SAP or third-party products or services developed outside of this project\n (\"External Products\").\n \"APIs\" means application programming interfaces, as well as their respective\n specifications and implementing code that allows software to communicate with\n other software.\n API Calls to External Products are not licensed under the open source license\n that governs this project. The use of such API Calls and related External\n Products are subject to applicable additional agreements with the relevant\n provider of the External Products. In no event shall the open source license\n that governs this project grant any rights in or to any External Products,or\n alter, expand or supersede any terms of the applicable additional agreements.\n If you have a valid license agreement with SAP for the use of a particular SAP\n External Product, then you may make use of any API Calls included in this\n project's code for that SAP External Product, subject to the terms of such\n license agreement. If you do not have a valid license agreement for the use of\n a particular SAP External Product, then you may only make use of any API Calls\n in this project for that SAP External Product for your internal, non-productive\n and non-commercial test and evaluation of such API Calls. Nothing herein grants\n you any rights to use or access any SAP External Product, or provide any third\n parties the right to use of access any SAP External Product, through API Calls."

[[annotations]]
path = "java/com.google.gwt.servlet/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 com.google.gwt.servlet contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/net.sf.marineapi/doc/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 doc contributors."
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "java/com.google.gwt.user/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 com.google.gwt.user contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/com.googlecode.java-diff-utils.test/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 com.googlecode.java-diff-utils.test contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and sailing-analytics contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/com.google.gwt.dev/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 com.google.gwt.dev contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/org.mp4parser.isoparser/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 org.mp4parser.isoparser contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/elemental2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 elemental2 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/org.json.simple/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 org.json.simple contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "java/org.openqa.selenium.osgi/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 org.openqa.selenium.osgi contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/com.google.gwt.ajaxloader/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 com.google.gwt.ajaxloader contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/com.googlecode.java-diff-utils/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 com.googlecode.java-diff-utils contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "java/com.sap.sailing.gwt.ui/qrcode/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 qrcode contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "ios/SAPTracker/src/xcode/SAPTracker/flags/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 flags contributors."
SPDX-License-Identifier = "MIT"
