source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
project 'SAPTracker.xcodeproj'

def pods
	pod 'AFNetworking', '2.5.0'
	pod 'AFNetworkActivityLogger', '2.0.3', :configurations => ['Debug']
	pod 'SVProgressHUD'
	pod 'TSMarkdownParser'
end

target 'SAPTracker' do
	pods
end

target 'SAPTrackerTests' do
	pods
end

# Update acknowledgements in build settings
post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-SAPTracker/Pods-SAPTracker-Acknowledgements.plist', 'SAPTracker/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
  FileUtils.cp_r('Pods/Target Support Files/Pods-SAPTracker/Pods-SAPTracker-Acknowledgements.markdown', 'SAPTracker/Acknowledgements.markdown', :remove_destination => true)
end