/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditRPD.java
 *
 * Created on 15.11.2011, 17:11:44
 */
package com.sap.sailing.domain.swisstimingadapter.test.ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.JOptionPane;

import com.sap.sailing.domain.swisstimingadapter.classes.messages.RPDMessage;
import com.sap.sailing.domain.swisstimingadapter.classes.messages.RacePositionDataElement;

/**
 *
 * @author D056866
 */
public class EditRPD extends javax.swing.JDialog {
    /**
     * 
     */
    private static final long serialVersionUID = -3828331008001452901L;
    private RPDMessage rpd;
    private List<RacePositionDataElement> rpdData;
    private DateFormat dateFormat;
    private DateFormat timeFormat;

    /** Creates new form EditRPD */
    public EditRPD(java.awt.Frame parent, boolean modal, RPDMessage pRpd) {
        super(parent, modal);
        initComponents();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        timeFormat = new SimpleDateFormat("HH:mm:ss");
        if (pRpd != null){
            this.rpd = pRpd;
        }
        else{
            rpd = new RPDMessage();
            try {
                rpd.setStartTime(timeFormat.parse("00:00:00"));
                rpd.setRaceTime(timeFormat.parse("00:00:00"));
                rpd.setDataTime(dateFormat.parse("2011-11-11T00:00:00+0100"));
            }
            catch (Exception e){
                
            }
        }
        rpdData = rpd.getRacePositionElements();
        jRPDData.setListData(rpdData.toArray(new RacePositionDataElement[0]));
        setValuesInUI();
    }
    
    private void setValuesInUI(){
        jRaceID.setText(rpd.getRaceId());
        jStatus.setText(""+rpd.getStatus());
        jDateTime.setText(""+(rpd.getDataTime() == null? "" : dateFormat.format(rpd.getDataTime())));
        jStartTime.setText(""+(rpd.getStartTime()==null?"" :timeFormat.format(rpd.getStartTime())));
        jRaceTime.setText(""+(rpd.getRaceTime()==null? "" :timeFormat.format(rpd.getRaceTime())));
        jNextMarkLeader.setText(""+rpd.getNextMarkLeader());
        jDistanceToNextMarkLeader.setText(""+rpd.getDistanceToNextMarkLeader());
    }
    
    private void getValuesFromUI(){
        rpd.setRaceId(jRaceID.getText());
        rpd.setStatus(Integer.parseInt(jStatus.getText()));
        try {
            rpd.setDataTime(dateFormat.parse(jDateTime.getText()));
            rpd.setStartTime(timeFormat.parse(jStartTime.getText()));
            rpd.setRaceTime(timeFormat.parse(jRaceTime.getText()));
        }
        catch (Exception e){
            
        }
        rpd.setNextMarkLeader(Integer.parseInt(jNextMarkLeader.getText()));
        rpd.setDistanceToNextMarkLeader(Double.parseDouble(jDistanceToNextMarkLeader.getText()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRaceID = new javax.swing.JTextField();
        jStatus = new javax.swing.JTextField();
        jDateTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jStartTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRaceTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jNextMarkLeader = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDistanceToNextMarkLeader = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDistanceToNextMark = new javax.swing.JTextField();
        jDistanceToLeader = new javax.swing.JTextField();
        jRank = new javax.swing.JTextField();
        jCOG = new javax.swing.JTextField();
        jVMG = new javax.swing.JTextField();
        jSOG = new javax.swing.JTextField();
        jLongitude = new javax.swing.JTextField();
        jLatitude = new javax.swing.JTextField();
        jAgeOfData = new javax.swing.JTextField();
        jBoatType = new javax.swing.JTextField();
        jSailNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRPDData = new javax.swing.JList<RacePositionDataElement>();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jALS = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jNextMark = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Race-ID:");

        jLabel2.setText("Status:");

        jLabel3.setText("Data Time:");

        jRaceID.setText("jTextField1");

        jStatus.setText("jTextField2");

        jDateTime.setText("jTextField3");

        jLabel4.setText("Starttime:");

        jStartTime.setText("jTextField4");

        jLabel5.setText("Racetime:");

        jRaceTime.setText("jTextField5");

        jLabel6.setText("Next Mark Leader:");

        jNextMarkLeader.setText("jTextField6");

        jLabel7.setText("Distance to next mark leader:");

        jDistanceToNextMarkLeader.setText("jTextField7");

        jLabel8.setText("Sail number:");

        jLabel9.setText("Boat type:");

        jLabel10.setText("Age of data:");

        jLabel11.setText("Latitude:");

        jLabel12.setText("Longitude");

        jLabel13.setText("SOG:");

        jLabel14.setText("VMG:");

        jLabel15.setText("COG:");

        jLabel16.setText("Rank:");

        jLabel17.setText("Distance to leader:");

        jLabel18.setText("Distance to next mark:");

        jDistanceToNextMark.setText("450.0");

        jDistanceToLeader.setText("23.30");

        jRank.setText("2");

        jCOG.setText("330.5");

        jVMG.setText("2.3");

        jSOG.setText("3.4");

        jLongitude.setText("45.234");

        jLatitude.setText("45.2343");

        jAgeOfData.setText("0");

        jBoatType.setText("1");

        jSailNumber.setText("s123");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jRPDData);

        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel19.setText("ALS");

        jALS.setText("3.3");

        jLabel20.setText("Next mark:");

        jNextMark.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jStartTime)
                            .addComponent(jRaceID)
                            .addComponent(jStatus)
                            .addComponent(jDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNextMarkLeader, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jRaceTime, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jDistanceToNextMarkLeader, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDistanceToNextMark))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jNextMark)
                                            .addComponent(jCOG)
                                            .addComponent(jALS)
                                            .addComponent(jBoatType)
                                            .addComponent(jAgeOfData)
                                            .addComponent(jLatitude)
                                            .addComponent(jLongitude)
                                            .addComponent(jSOG)
                                            .addComponent(jVMG)
                                            .addComponent(jSailNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDistanceToLeader, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                            .addComponent(jRank, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRaceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRaceTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jNextMarkLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDistanceToNextMarkLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSailNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jBoatType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jAgeOfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jSOG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jVMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jALS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCOG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jNextMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jDistanceToLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jDistanceToNextMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            rpdData.add(new RacePositionDataElement(
                jSailNumber.getText(), 
                Integer.parseInt(jBoatType.getText()), 
                Long.parseLong(jAgeOfData.getText()), 
                Double.parseDouble(jLatitude.getText()), 
                Double.parseDouble(jLongitude.getText()), 
                Double.parseDouble(jSOG.getText()), 
                Double.parseDouble(jVMG.getText()), 
                Double.parseDouble(jALS.getText()),
                Double.parseDouble(jCOG.getText()),
                Integer.parseInt(jNextMark.getText()),
                Integer.parseInt(jRank.getText()), 
                Double.parseDouble(jDistanceToLeader.getText()), 
                Double.parseDouble(jDistanceToNextMark.getText())));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Invalid input paramters!", "Invalid input", JOptionPane.ERROR_MESSAGE);
        }
        jRPDData.setListData(rpdData.toArray(new RacePositionDataElement[0]));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (RacePositionDataElement o : jRPDData.getSelectedValuesList())
            rpdData.remove(o);
        jRPDData.setListData(rpdData.toArray(new RacePositionDataElement[0]));
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        getValuesFromUI();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public RPDMessage getMessage(){
        return rpd;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jALS;
    private javax.swing.JTextField jAgeOfData;
    private javax.swing.JTextField jBoatType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jCOG;
    private javax.swing.JTextField jDateTime;
    private javax.swing.JTextField jDistanceToLeader;
    private javax.swing.JTextField jDistanceToNextMark;
    private javax.swing.JTextField jDistanceToNextMarkLeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLatitude;
    private javax.swing.JTextField jLongitude;
    private javax.swing.JTextField jNextMark;
    private javax.swing.JTextField jNextMarkLeader;
    private javax.swing.JList<RacePositionDataElement> jRPDData;
    private javax.swing.JTextField jRaceID;
    private javax.swing.JTextField jRaceTime;
    private javax.swing.JTextField jRank;
    private javax.swing.JTextField jSOG;
    private javax.swing.JTextField jSailNumber;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jStartTime;
    private javax.swing.JTextField jStatus;
    private javax.swing.JTextField jVMG;
    // End of variables declaration//GEN-END:variables
}
