/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditABS.java
 *
 * Created on 15.11.2011, 16:30:05
 */
package com.sap.sailing.domain.swisstimingadapter.test.ui;

import com.sap.sailing.domain.swisstimingadapter.classes.messages.ABSMessage;

/**
 *
 * @author D056866
 */
public class EditABS extends javax.swing.JDialog {
    /**
     * 
     */
    private static final long serialVersionUID = 3022584027805324921L;
    private ABSMessage abs;

    /** Creates new form EditABS */
    public EditABS(java.awt.Frame parent, boolean modal, ABSMessage pAbs) {
        super(parent, modal);
        initComponents();
        if (pAbs != null)
            this.abs = pAbs;
        else
            this.abs = new ABSMessage();
        jRacedID.setText(abs.getRaceId());
        jLeg.setText(abs.getLeg());
        jSailNumber.setText(abs.getSailNumber());
        jSpeed.setText(""+abs.getSpeed());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRacedID = new javax.swing.JTextField();
        jLeg = new javax.swing.JTextField();
        jSailNumber = new javax.swing.JTextField();
        jSpeed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Race-ID:");

        jRacedID.setText("jTextField1");

        jLeg.setText("jTextField2");

        jSailNumber.setText("jTextField3");

        jSpeed.setText("jTextField4");

        jLabel2.setText("Leg:");

        jLabel3.setText("Sail Number:");

        jLabel4.setText("Speed:");

        jOk.setText("Ok");
        jOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpeed)
                            .addComponent(jSailNumber)
                            .addComponent(jLeg)
                            .addComponent(jRacedID, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRacedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSailNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkActionPerformed
        // TODO add your handling code here:
        abs.setLeg(jLeg.getText());
        abs.setRaceId(jRacedID.getText());
        abs.setSailNumber(jSailNumber.getText());
        abs.setSpeed(Double.parseDouble(jSpeed.getText()));
        dispose();
    }//GEN-LAST:event_jOkActionPerformed

    public ABSMessage getMessage(){
        return abs;
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLeg;
    private javax.swing.JButton jOk;
    private javax.swing.JTextField jRacedID;
    private javax.swing.JTextField jSailNumber;
    private javax.swing.JTextField jSpeed;
    // End of variables declaration//GEN-END:variables
}
