package com.sap.sailing.mongodb.impl;

public enum FieldNames {
    TIME_AS_MILLIS, KNOT_SPEED, DEGREE_BEARING, LAT_DEG, LNG_DEG, EVENT_NAME, RACE_NAME, WIND_SOURCE_NAME, WIND,
    TT_CONFIG_NAME, TT_CONFIG_JSON_URL, TT_CONFIG_LIVE_DATA_URI, TT_CONFIG_STORED_DATA_URI
}
