package com.sap.sailing.mongodb.impl;

public enum FieldNames {
    // general:
    TIME_AS_MILLIS, KNOT_SPEED, DEGREE_BEARING, LAT_DEG, LNG_DEG,
    EVENT_NAME, RACE_NAME,
    
    // wind:
    WIND_SOURCE_NAME, WIND,
    
    // TracTrac configuration parameters:
    TT_CONFIG_NAME, TT_CONFIG_JSON_URL, TT_CONFIG_LIVE_DATA_URI, TT_CONFIG_STORED_DATA_URI,
    
    // leaderboard:
    LEADERBOARD_NAME, LEADERBOARD_COLUMNS, LEADERBOARD_COLUMN_NAME, LEADERBOARD_IS_MEDAL_RACE_COLUMN,
    LEADERBOARD_CARRIED_POINTS, LEADERBOARD_SCORE_CORRECTIONS, LEADERBOARD_DISCARDING_THRESHOLDS
}
