#!/bin/bash

# Script to deploy on an instance that has an ephemeral volume as /dev/nvme0n1 (adjust env var EPHEMERAL_VOLUME if different)
# Ensures the partition is xfs-formatted, any existing partition contents will be overwritten if formatted otherwise.
# An existing xfs partition will be left alone.
EPHEMERAL_VOLUME_NAME=$(
  # List all block devices and find those named nvme...
  for i in $(lsblk | grep -o "nvme[0-9][0-9]\?n[0-9]" | sort -u); do
    # If they don't have any partitions, then...
    if ! lsblk | grep -o "${i}p[0-9]\+" 2>&1 >/dev/null; then
      # ...check whether they are EBS devices
      /sbin/ebsnvme-id -u "/dev/$i" >/dev/null
      # If not, list their name because then they must be ephemeral instance storage
      if [[ $? -ne 0 ]]; then
        echo "${i}"
      fi
    fi
  done 2>/dev/null | head -n 1 )
if [ -n "${EPHEMERAL_VOLUME_NAME}" ]; then
  EPHEMERAL_VOLUME=/dev/${EPHEMERAL_VOLUME_NAME}
  FSTYPE=$(blkid -p $EPHEMERAL_VOLUME -s TYPE -o value)
  if [ "$FSTYPE" = "" ]; then
    echo FSTYPE was empty, creating swap partition
    mkswap $EPHEMERAL_VOLUME
    swapon --priority 2 -a $EPHEMERAL_VOLUME
  else
    echo "FSTYPE was $FSTYPE, not touching"
  fi
else
  echo "No ephemeral partition found. Not creating any swap partition."
fi
