#!/bin/bash

# Script to deploy on an instance that has an ephemeral volume as /dev/nvme0n1 (adjust env var PARTITION if different)
# Ensures the partition is xfs-formatted, any existing partition contents will be overwritten if formatted otherwise.
# An existing xfs partition will be left alone.

METADATA=$( /bin/ec2-metadata -d | sed -e 's/^user-data: //' )
echo "Metadata: ${METADATA}"
if echo "${METADATA}" | grep -q "^image-upgrade$"; then
  echo "Image upgrade; not trying to mount/format ephemeral volume; calling imageupgrade.sh instead..."
  imageupgrade.sh
else
  echo "No image upgrade; looking for ephemeral volume and trying to format with xfs..."
  PARTITION=/dev/nvme0n1
  if [ \! -e $PARTITION ]; then
    PARTITION=/dev/xvdb
  fi
  if [ \! -e $PARTITION ]; then
    echo "Neither /dev/nvme0n1 nor /dev/xvdb partition found; not formatting/mounting ephemeral volume"
  elif cat /proc/mounts | awk '{print $1;}' | grep "${PARTITION}"; then
    echo "Partition ${PARTITION} already mounted; not formatting/mounting ephemeral volume"
  else
    FSTYPE=$(blkid -p $PARTITION -s TYPE -o value)
    if [ "$FSTYPE" != "xfs" ]; then
      echo FSTYPE was "$FSTYPE" but should have been xfs. Formatting $PARTITION...
      mkfs.xfs -f $PARTITION
    else
      echo FSTYPE was "$FSTYPE" which is just right :-\)
    fi
    # mount the thing to /var/lib/mongo
    mount $PARTITION /var/lib/mongo
  fi
fi
