FROM buildpack-deps:stretch-scm
LABEL maintainer=axel.uhl@sap.com
# Download and extract the SAP JVM 8
ENV PATH=${PATH}:/opt/sapjvm_8/bin
ENV JAVA_HOME=/opt/sapjvm_8
WORKDIR /opt
RUN apt-get update \
 && apt-get install -y wget unzip \
 && curl --cookie eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt "https://tools.hana.ondemand.com/additional/sapjvm-8.1.051-linux-x64.zip" --output sapjvm8-linux-x64.zip \
 && unzip sapjvm8-linux-x64.zip \
 && rm sapjvm8-linux-x64.zip \
 && echo "export JAVA_HOME=/opt/sapjvm_8; export PATH=\${PATH}:/opt/sapjvm_8/bin" > /etc/profile.d/javahome.sh
