#!/bin/bash
helm install --name cert-manager stable/cert-manager --version v0.4.1 --set ingressShim.defaultIssuerName=letsencrypt-prod --set ingressShim.defaultIssuerKind=ClusterIssuer
helm upgrade cert-manager stable/cert-manager
cat << EOF| kubectl apply -f -
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    #server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: axel.uhl@sap.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
EOF
