#!/bin/bash
# If helm executable is missing, get it from https://github.com/helm/helm/releases
# and for Linux amd64 in particular grab it from https://storage.googleapis.com/kubernetes-helm/helm-v2.12.0-rc.1-linux-amd64.tar.gz
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}' 
helm init
helm list
helm repo update
