#!/bin/bash
release=$1
if [ "${release}" = "" ]; then
  SET_LATEST=1
  release=$(wget -O - https://releases.sapsailing.com/ 2>/dev/null | grep 'build-[0-9]\{10\}' | tail -1 | sed -e 's/^.*\(build-[0-9]*\).*$/\1/')
  echo Latest release is ${release}
fi
GITROOT="`dirname $0`/.."
DOCKERDIR="${GITROOT}/docker"
DOCKERFILE="$DOCKERDIR/Dockerfile"
echo "Copying files from GITROOT $GITROOT into Docker workspace"
cp "$GITROOT/java/target/env.sh" "$DOCKERDIR"
cp "$GITROOT/java/target/start" "$DOCKERDIR"
cp "$GITROOT/java/target/configuration/JavaSE-11.profile" "$DOCKERDIR"
cd "$DOCKERDIR"
docker build --build-arg RELEASE=${release} -t ghcr.io/sap/sailing-analytics:${release} .
echo "Cleaning up..."
rm start env.sh JavaSE-11.profile
docker push ghcr.io/sap/sailing-analytics:${release}
if [ "$SET_LATEST" = "1" ]; then
  docker tag ghcr.io/sap/sailing-analytics:${release} ghcr.io/sap/sailing-analytics:latest
  docker push ghcr.io/sap/sailing-analytics:latest
fi
