#!/bin/bash
release=$1
if [ "${release}" = "" ]; then
  SET_LATEST=1
  release=$(wget -O - http://releases.sapsailing.com/ 2>/dev/null | grep 'sapmachine17-[0-9]\{10\}' | tail -1 | sed -e 's/^.*\(sapmachine17-[0-9]*\).*$/\1/')
  echo Latest release is ${release}
fi
GITROOT="`dirname $0`/.."
DOCKERDIR="${GITROOT}/docker"
DOCKERFILE="$DOCKERDIR/Dockerfile"
FILES_TO_COPY_FROM_JAVA_TARGET="env.sh start configuration/JavaSE-11.profile"
echo "Copying files from GITROOT $GITROOT into Docker workspace"
for f in ${FILES_TO_COPY_FROM_JAVA_TARGET}; do
  cp "${GITROOT}/java/target/${f}" "$DOCKERDIR"
done
cd "$DOCKERDIR"
docker build --build-arg RELEASE=${release} -t sapsailing_on_sapmachine17:${release} -f Dockerfile_sapsailing_on_sapmachine17 .
echo "Cleaning up..."
for f in ${FILES_TO_COPY_FROM_JAVA_TARGET}; do
  rm "`basename ${f}`"
done
docker tag sapsailing_on_sapmachine17:${release} docker.sapsailing.com/sapsailing_on_sapmachine17:${release}
docker push docker.sapsailing.com/sapsailing_on_sapmachine17:${release}
if [ "$SET_LATEST" = "1" ]; then
  docker tag sapsailing_on_sapmachine17:${release} docker.sapsailing.com/sapsailing_on_sapmachine17:latest
  docker push docker.sapsailing.com/sapsailing_on_sapmachine17:latest
fi
