#!/bin/bash
release=$1
if [ "$release" = "" ]; then
  SET_LATEST=1
  release=$(wget -O - http://releases.sapsailing.com/ 2>/dev/null | grep build- | tail -1 | sed -e 's/^.*\(build-[0-9]*\).*$/\1/')
  echo Latest release is $release
fi
GITROOT="`dirname $0`/.."
DOCKERDIR="${GITROOT}/docker"
DOCKERFILE="$DOCKERDIR/Dockerfile-raspi"
echo "Copying files from GITROOT $GITROOT into Docker workspace"
cp "$GITROOT/java/target/env.sh" "$DOCKERDIR"
cp "$GITROOT/java/target/start" "$DOCKERDIR"
cp "$GITROOT/java/target/configuration/JavaSE-11.profile" "$DOCKERDIR"
cat ${DOCKERFILE}.tpl | sed -e "s/RELEASE/${release}/g" >${DOCKERFILE}
cd "$DOCKERDIR"
docker build -t sapsailing:${release}-raspi -f ${DOCKERFILE} .
echo "Cleaning up..."
rm start env.sh JavaSE-11.profile ${Dockerfile}
docker tag sapsailing:${release}-raspi donaldduck70/sapsailing:${release}-raspi
docker push donaldduck70/sapsailing:${release}-raspi
if [ "$SET_LATEST" = "1" ]; then
  docker tag sapsailing:${release}-raspi donaldduck70/sapsailing:latest-raspi
  docker push donaldduck70/sapsailing:latest-raspi
fi
