package com.sap.sailing.domain.racelogtracking.impl;

import com.sap.sailing.domain.racelogtracking.DeviceIdentifierStringSerializationHandler;

public class PingDeviceIdentifierStringSerializationHandler extends PingDeviceIdentifierSerializationHandler
implements DeviceIdentifierStringSerializationHandler {

}
