package com.sap.sailing.domain.racelogtracking.impl;

import com.sap.sailing.domain.racelogtracking.DeviceIdentifierStringSerializationHandler;
import com.sap.sailing.domain.racelogtracking.SmartphoneUUIDSerializationHandler;

public class SmartphoneUUIDStringSerializationHandler extends SmartphoneUUIDSerializationHandler
implements DeviceIdentifierStringSerializationHandler {

}
