package com.sap.sailing.domain.igtimiadapter.persistence.impl;

public enum FieldNames {
    IGTIMI_DEVICES_ID, IGTIMI_DEVICES_SERIAL_NUMBER, IGTIMI_DEVICES_NAME, IGTIMI_DEVICES_SERVICE_TAG,
    IGTIMI_RESOURCES_ID, IGTIMI_RESOURCES_START_TIME_MILLIS, IGTIMI_RESOURCES_END_TIME_MILLIS, IGTIMI_RESOURCES_DEVICE_SERIAL_NUMBER, IGTIMI_RESOURCES_DATA_TYPES,
    IGTIMI_DATA_ACCESS_WINDOWS_ID, IGTIMI_DATA_ACCESS_WINDOWS_START_TIME_MILLIS, IGTIMI_DATA_ACCESS_WINDOWS_END_TIME_MILLIS, IGTIMI_DATA_ACCESS_WINDOWS_DEVICE_SERIAL_NUMBER,
    IGTIMI_MESSAGES_TIMESTAMP, IGTIMI_MESSAGES_DEVICE_SERIAL_NUMBER, IGTIMI_MESSAGES_PROTOBUF_MESSAGE;
}
