#!/bin/bash
killall autossh
sleep 2
# Tunnel to cloud MongoDB on port 10203 with reverse tunnels for MongoDB on localhost:10201 and through tunnel on localhost:10202 to P1 #2
autossh -M 20500 -f -A -N -L 22443:sapsailing.com:443 -L 22222:sapsailing.com:22 -R 9443:localhost:9443 -R '*:8888:localhost:8888' -R 10201:localhost:10201 -L 10203:localhost:10203 -L 5673:rabbit-ap-northeast-1.sapsailing.com:5672 -L 15673:localhost:15673 -L 5675:rabbit.internal.sapsailing.com:5672 -L 15675:rabbit.internal.sapsailing.com:15672 -L 443:security-service.sapsailing.com:443 -R 18122:localhost:22 ec2-user@tokyo-ssh.sapsailing.com
sleep 2
# Tunnel to other laptop P1 #2, tunneling to MongoDB running on 10202, mapping to local port 10202
autossh -M 20502 -f -A -N -L 10202:localhost:10202 -R 10201:localhost:10201 sailing@sap-p1-2
sleep 2
# Tunnel to localhost for TracTrac A port forwards
tractrac-A
