//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Boat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Boat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BoatID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BoatName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SailNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Boat")
public class Boat {

    @XmlAttribute(name = "BoatID", required = true)
    protected String boatID;
    @XmlAttribute(name = "BoatName")
    protected String boatName;
    @XmlAttribute(name = "SailNumber", required = true)
    protected String sailNumber;

    /**
     * Gets the value of the boatID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoatID() {
        return boatID;
    }

    /**
     * Sets the value of the boatID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoatID(String value) {
        this.boatID = value;
    }

    /**
     * Gets the value of the boatName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoatName() {
        return boatName;
    }

    /**
     * Sets the value of the boatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoatName(String value) {
        this.boatName = value;
    }

    /**
     * Gets the value of the sailNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSailNumber() {
        return sailNumber;
    }

    /**
     * Sets the value of the sailNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSailNumber(String value) {
        this.sailNumber = value;
    }

}
