//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DivisionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DivisionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FleetRace"/>
 *     &lt;enumeration value="TeamRace"/>
 *     &lt;enumeration value="MatchRace"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DivisionType")
@XmlEnum
public enum DivisionType {

    @XmlEnumValue("FleetRace")
    FLEET_RACE("FleetRace"),
    @XmlEnumValue("TeamRace")
    TEAM_RACE("TeamRace"),
    @XmlEnumValue("MatchRace")
    MATCH_RACE("MatchRace");
    private final String value;

    DivisionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DivisionType fromValue(String v) {
        for (DivisionType c: DivisionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
