//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Division complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Division">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="SeriesResult" type="{}SeriesResult" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RaceResult" type="{}RaceResult" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TRResult" type="{}TRResult" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="Type" type="{}DivisionType" default="FleetRace" />
 *       &lt;attribute name="DivisionID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IFDivisionID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IFClassID" type="{}IFClassCode" />
 *       &lt;attribute name="Gender" type="{}EventGender" />
 *       &lt;attribute name="Disabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Division", propOrder = {
    "seriesResultOrRaceResultOrTRResult"
})
public class Division {

    @XmlElements({
        @XmlElement(name = "SeriesResult", type = SeriesResult.class),
        @XmlElement(name = "RaceResult", type = RaceResult.class),
        @XmlElement(name = "TRResult", type = TRResult.class)
    })
    protected List<Object> seriesResultOrRaceResultOrTRResult;
    @XmlAttribute(name = "Type")
    protected DivisionType type;
    @XmlAttribute(name = "DivisionID", required = true)
    protected String divisionID;
    @XmlAttribute(name = "IFDivisionID")
    protected String ifDivisionID;
    @XmlAttribute(name = "Title", required = true)
    protected String title;
    @XmlAttribute(name = "IFClassID")
    protected String ifClassID;
    @XmlAttribute(name = "Gender")
    protected EventGender gender;
    @XmlAttribute(name = "Disabled")
    protected Boolean disabled;

    /**
     * Gets the value of the seriesResultOrRaceResultOrTRResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seriesResultOrRaceResultOrTRResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeriesResultOrRaceResultOrTRResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SeriesResult }
     * {@link RaceResult }
     * {@link TRResult }
     * 
     * 
     */
    public List<Object> getSeriesResultOrRaceResultOrTRResult() {
        if (seriesResultOrRaceResultOrTRResult == null) {
            seriesResultOrRaceResultOrTRResult = new ArrayList<Object>();
        }
        return this.seriesResultOrRaceResultOrTRResult;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DivisionType }
     *     
     */
    public DivisionType getType() {
        if (type == null) {
            return DivisionType.FLEET_RACE;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DivisionType }
     *     
     */
    public void setType(DivisionType value) {
        this.type = value;
    }

    /**
     * Gets the value of the divisionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivisionID() {
        return divisionID;
    }

    /**
     * Sets the value of the divisionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisionID(String value) {
        this.divisionID = value;
    }

    /**
     * Gets the value of the ifDivisionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIFDivisionID() {
        return ifDivisionID;
    }

    /**
     * Sets the value of the ifDivisionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIFDivisionID(String value) {
        this.ifDivisionID = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the ifClassID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIFClassID() {
        return ifClassID;
    }

    /**
     * Sets the value of the ifClassID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIFClassID(String value) {
        this.ifClassID = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link EventGender }
     *     
     */
    public EventGender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventGender }
     *     
     */
    public void setGender(EventGender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the disabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisabled() {
        return disabled;
    }

    /**
     * Sets the value of the disabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisabled(Boolean value) {
        this.disabled = value;
    }

}
