//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventGender.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventGender">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Men"/>
 *     &lt;enumeration value="Women"/>
 *     &lt;enumeration value="Open"/>
 *     &lt;enumeration value="Mixed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventGender")
@XmlEnum
public enum EventGender {


    /**
     * Men
     * 
     */
    @XmlEnumValue("Men")
    MEN("Men"),

    /**
     * Women
     * 
     */
    @XmlEnumValue("Women")
    WOMEN("Women"),

    /**
     * Open
     * 
     */
    @XmlEnumValue("Open")
    OPEN("Open"),

    /**
     * Mixed
     * 
     */
    @XmlEnumValue("Mixed")
    MIXED("Mixed");
    private final String value;

    EventGender(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventGender fromValue(String v) {
        for (EventGender c: EventGender.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
