//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Race" type="{}Race" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Division" type="{}Division" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RegattaSeriesResult" type="{}RegattaSeriesResult" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="EventID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IFEventID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Type" type="{}EventType" default="Regatta" />
 *       &lt;attribute name="Title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "raceOrDivisionOrRegattaSeriesResult"
})
public class Event {

    @XmlElements({
        @XmlElement(name = "Race", type = Race.class),
        @XmlElement(name = "Division", type = Division.class),
        @XmlElement(name = "RegattaSeriesResult", type = RegattaSeriesResult.class)
    })
    protected List<Object> raceOrDivisionOrRegattaSeriesResult;
    @XmlAttribute(name = "EventID", required = true)
    protected String eventID;
    @XmlAttribute(name = "IFEventID")
    protected String ifEventID;
    @XmlAttribute(name = "Type")
    protected EventType type;
    @XmlAttribute(name = "Title")
    protected String title;

    /**
     * Gets the value of the raceOrDivisionOrRegattaSeriesResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the raceOrDivisionOrRegattaSeriesResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRaceOrDivisionOrRegattaSeriesResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Race }
     * {@link Division }
     * {@link RegattaSeriesResult }
     * 
     * 
     */
    public List<Object> getRaceOrDivisionOrRegattaSeriesResult() {
        if (raceOrDivisionOrRegattaSeriesResult == null) {
            raceOrDivisionOrRegattaSeriesResult = new ArrayList<Object>();
        }
        return this.raceOrDivisionOrRegattaSeriesResult;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventID(String value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the ifEventID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIFEventID() {
        return ifEventID;
    }

    /**
     * Sets the value of the ifEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIFEventID(String value) {
        this.ifEventID = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getType() {
        if (type == null) {
            return EventType.REGATTA;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setType(EventType value) {
        this.type = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
