//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IFBoatStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IFBoatStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ARB"/>
 *     &lt;enumeration value="BFD"/>
 *     &lt;enumeration value="DGM"/>
 *     &lt;enumeration value="DNC"/>
 *     &lt;enumeration value="DNE"/>
 *     &lt;enumeration value="DNF"/>
 *     &lt;enumeration value="DNS"/>
 *     &lt;enumeration value="DPI"/>
 *     &lt;enumeration value="DSQ"/>
 *     &lt;enumeration value="OCS"/>
 *     &lt;enumeration value="PTS"/>
 *     &lt;enumeration value="RAF"/>
 *     &lt;enumeration value="RDG"/>
 *     &lt;enumeration value="RET"/>
 *     &lt;enumeration value="SCP"/>
 *     &lt;enumeration value="ZFP"/>
 *     &lt;enumeration value="RTD"/>
 *     &lt;enumeration value="UFD"/>
 *     &lt;enumeration value="TLE"/>
 *     &lt;enumeration value="STP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IFBoatStatus")
@XmlEnum
public enum IFBoatStatus {


    /**
     * Scoring penalty after arbitration
     * 
     */
    ARB,

    /**
     * Disqualification under rule 30.3
     * 
     */
    BFD,

    /**
     * Disqualification for gross misconduct not excludable under rule 90.3(b)
     * 
     */
    DGM,

    /**
     * Did not start; did not come to the starting area
     * 
     */
    DNC,

    /**
     * Disqualification (other than DGM) not excludable under rule 90.3(b)
     * 
     */
    DNE,

    /**
     * Did not finish
     * 
     */
    DNF,

    /**
     * Did not start (other than DNC and OCS)
     * 
     */
    DNS,

    /**
     * Discretionary penalty imposed
     * 
     */
    DPI,

    /**
     * Disqualification
     * 
     */
    DSQ,

    /**
     * Did not start; on the course side of the starting line at her starting signal and failed to start, or broke rule 30.1
     * 
     */
    OCS,

    /**
     * Scoring penalty for a yellow flag after the finish
     * 
     */
    PTS,

    /**
     * Retired after finishing
     * 
     */
    RAF,

    /**
     * Redress given
     * 
     */
    RDG,

    /**
     * Retired
     * 
     */
    RET,

    /**
     * Took a Scoring Penalty under rule 44.3(a)
     * 
     */
    SCP,

    /**
     *  20% penalty under rule 30.2
     * 
     */
    ZFP,

    /**
     * Retired
     * 
     */
    RTD,

    /** 
     * Uniform Flag Disqualification 
     */
    UFD,
    /**
     *  Time limit Expired 
     */
    TLE,
    /** 
     * Standard Penalty by Race Committee; gives a certain number of penalty points on top of rank-inferred score 
     */
    STP;
    
    public String value() {
        return name();
    }

    public static IFBoatStatus fromValue(String v) {
        return valueOf(v);
    }

}
