//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IFCfcnStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IFCfcnStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Current"/>
 *     &lt;enumeration value="Pending"/>
 *     &lt;enumeration value="Expired"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IFCfcnStatus")
@XmlEnum
public enum IFCfcnStatus {


    /**
     * Current
     * 
     */
    @XmlEnumValue("Current")
    CURRENT("Current"),

    /**
     * Pending
     * 
     */
    @XmlEnumValue("Pending")
    PENDING("Pending"),

    /**
     * Expired
     * 
     */
    @XmlEnumValue("Expired")
    EXPIRED("Expired"),

    /**
     * None
     * 
     */
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    IFCfcnStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IFCfcnStatus fromValue(String v) {
        for (IFCfcnStatus c: IFCfcnStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
