//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IFNationCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IFNationCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AFG"/>
 *     &lt;enumeration value="AHO"/>
 *     &lt;enumeration value="ALB"/>
 *     &lt;enumeration value="ALG"/>
 *     &lt;enumeration value="ANA"/>
 *     &lt;enumeration value="AND"/>
 *     &lt;enumeration value="ANG"/>
 *     &lt;enumeration value="ANT"/>
 *     &lt;enumeration value="ARG"/>
 *     &lt;enumeration value="ARM"/>
 *     &lt;enumeration value="ARU"/>
 *     &lt;enumeration value="ASA"/>
 *     &lt;enumeration value="AUS"/>
 *     &lt;enumeration value="AUT"/>
 *     &lt;enumeration value="AZE"/>
 *     &lt;enumeration value="BAH"/>
 *     &lt;enumeration value="BAN"/>
 *     &lt;enumeration value="BAR"/>
 *     &lt;enumeration value="BDI"/>
 *     &lt;enumeration value="BEL"/>
 *     &lt;enumeration value="BEN"/>
 *     &lt;enumeration value="BER"/>
 *     &lt;enumeration value="BHU"/>
 *     &lt;enumeration value="BIH"/>
 *     &lt;enumeration value="BIR"/>
 *     &lt;enumeration value="BIZ"/>
 *     &lt;enumeration value="BLR"/>
 *     &lt;enumeration value="BOL"/>
 *     &lt;enumeration value="BOT"/>
 *     &lt;enumeration value="BRA"/>
 *     &lt;enumeration value="BRN"/>
 *     &lt;enumeration value="BRU"/>
 *     &lt;enumeration value="BUL"/>
 *     &lt;enumeration value="BUR"/>
 *     &lt;enumeration value="BWI"/>
 *     &lt;enumeration value="CAF"/>
 *     &lt;enumeration value="CAL"/>
 *     &lt;enumeration value="CAM"/>
 *     &lt;enumeration value="CAN"/>
 *     &lt;enumeration value="CAY"/>
 *     &lt;enumeration value="CGO"/>
 *     &lt;enumeration value="CHA"/>
 *     &lt;enumeration value="CHI"/>
 *     &lt;enumeration value="CHN"/>
 *     &lt;enumeration value="CIV"/>
 *     &lt;enumeration value="CMR"/>
 *     &lt;enumeration value="COD"/>
 *     &lt;enumeration value="COK"/>
 *     &lt;enumeration value="COL"/>
 *     &lt;enumeration value="COM"/>
 *     &lt;enumeration value="CPV"/>
 *     &lt;enumeration value="CRC"/>
 *     &lt;enumeration value="CRO"/>
 *     &lt;enumeration value="CUB"/>
 *     &lt;enumeration value="CUR"/>
 *     &lt;enumeration value="CYP"/>
 *     &lt;enumeration value="CZE"/>
 *     &lt;enumeration value="DEN"/>
 *     &lt;enumeration value="DJI"/>
 *     &lt;enumeration value="DMA"/>
 *     &lt;enumeration value="DOM"/>
 *     &lt;enumeration value="ECU"/>
 *     &lt;enumeration value="EGY"/>
 *     &lt;enumeration value="ERI"/>
 *     &lt;enumeration value="ESA"/>
 *     &lt;enumeration value="ESP"/>
 *     &lt;enumeration value="EST"/>
 *     &lt;enumeration value="ETH"/>
 *     &lt;enumeration value="EUA"/>
 *     &lt;enumeration value="EUN"/>
 *     &lt;enumeration value="FAR"/>
 *     &lt;enumeration value="FGU"/>
 *     &lt;enumeration value="FIJ"/>
 *     &lt;enumeration value="FIN"/>
 *     &lt;enumeration value="FRA"/>
 *     &lt;enumeration value="FRG"/>
 *     &lt;enumeration value="FSM"/>
 *     &lt;enumeration value="GAB"/>
 *     &lt;enumeration value="GAM"/>
 *     &lt;enumeration value="GBR"/>
 *     &lt;enumeration value="GBS"/>
 *     &lt;enumeration value="GDR"/>
 *     &lt;enumeration value="GEO"/>
 *     &lt;enumeration value="GEQ"/>
 *     &lt;enumeration value="GER"/>
 *     &lt;enumeration value="GHA"/>
 *     &lt;enumeration value="GIB"/>
 *     &lt;enumeration value="GRE"/>
 *     &lt;enumeration value="GRN"/>
 *     &lt;enumeration value="GUA"/>
 *     &lt;enumeration value="GUD"/>
 *     &lt;enumeration value="GUI"/>
 *     &lt;enumeration value="GUM"/>
 *     &lt;enumeration value="GUY"/>
 *     &lt;enumeration value="HAI"/>
 *     &lt;enumeration value="HKG"/>
 *     &lt;enumeration value="HON"/>
 *     &lt;enumeration value="HUN"/>
 *     &lt;enumeration value="INA"/>
 *     &lt;enumeration value="IND"/>
 *     &lt;enumeration value="IOA"/>
 *     &lt;enumeration value="IRI"/>
 *     &lt;enumeration value="IRL"/>
 *     &lt;enumeration value="IRQ"/>
 *     &lt;enumeration value="ISL"/>
 *     &lt;enumeration value="ISR"/>
 *     &lt;enumeration value="ISV"/>
 *     &lt;enumeration value="ITA"/>
 *     &lt;enumeration value="IVB"/>
 *     &lt;enumeration value="JAM"/>
 *     &lt;enumeration value="JOR"/>
 *     &lt;enumeration value="JPN"/>
 *     &lt;enumeration value="KAZ"/>
 *     &lt;enumeration value="KEN"/>
 *     &lt;enumeration value="KGZ"/>
 *     &lt;enumeration value="KIR"/>
 *     &lt;enumeration value="KOR"/>
 *     &lt;enumeration value="KOS"/>
 *     &lt;enumeration value="KSA"/>
 *     &lt;enumeration value="KUW"/>
 *     &lt;enumeration value="LAO"/>
 *     &lt;enumeration value="LAT"/>
 *     &lt;enumeration value="LBA"/>
 *     &lt;enumeration value="LBR"/>
 *     &lt;enumeration value="LCA"/>
 *     &lt;enumeration value="LES"/>
 *     &lt;enumeration value="LIB"/>
 *     &lt;enumeration value="LIE"/>
 *     &lt;enumeration value="LTU"/>
 *     &lt;enumeration value="LUX"/>
 *     &lt;enumeration value="MAC"/>
 *     &lt;enumeration value="MAD"/>
 *     &lt;enumeration value="MAR"/>
 *     &lt;enumeration value="MAS"/>
 *     &lt;enumeration value="MAW"/>
 *     &lt;enumeration value="MDA"/>
 *     &lt;enumeration value="MDV"/>
 *     &lt;enumeration value="MEX"/>
 *     &lt;enumeration value="MGL"/>
 *     &lt;enumeration value="MHL"/>
 *     &lt;enumeration value="MKD"/>
 *     &lt;enumeration value="MLI"/>
 *     &lt;enumeration value="MLT"/>
 *     &lt;enumeration value="MNE"/>
 *     &lt;enumeration value="MNT"/>
 *     &lt;enumeration value="MON"/>
 *     &lt;enumeration value="MOZ"/>
 *     &lt;enumeration value="MRI"/>
 *     &lt;enumeration value="MRN"/>
 *     &lt;enumeration value="MTN"/>
 *     &lt;enumeration value="MYA"/>
 *     &lt;enumeration value="NAM"/>
 *     &lt;enumeration value="NCA"/>
 *     &lt;enumeration value="NED"/>
 *     &lt;enumeration value="NEP"/>
 *     &lt;enumeration value="NGR"/>
 *     &lt;enumeration value="NIG"/>
 *     &lt;enumeration value="NMI"/>
 *     &lt;enumeration value="NOR"/>
 *     &lt;enumeration value="NRU"/>
 *     &lt;enumeration value="NZL"/>
 *     &lt;enumeration value="OMA"/>
 *     &lt;enumeration value="PAK"/>
 *     &lt;enumeration value="PAN"/>
 *     &lt;enumeration value="PAR"/>
 *     &lt;enumeration value="PER"/>
 *     &lt;enumeration value="PHI"/>
 *     &lt;enumeration value="PLE"/>
 *     &lt;enumeration value="PLW"/>
 *     &lt;enumeration value="PNG"/>
 *     &lt;enumeration value="POL"/>
 *     &lt;enumeration value="POR"/>
 *     &lt;enumeration value="PRK"/>
 *     &lt;enumeration value="PUR"/>
 *     &lt;enumeration value="QAT"/>
 *     &lt;enumeration value="REU"/>
 *     &lt;enumeration value="RHO"/>
 *     &lt;enumeration value="ROM"/>
 *     &lt;enumeration value="ROU"/>
 *     &lt;enumeration value="RSA"/>
 *     &lt;enumeration value="RUS"/>
 *     &lt;enumeration value="RWA"/>
 *     &lt;enumeration value="SAM"/>
 *     &lt;enumeration value="SEN"/>
 *     &lt;enumeration value="SEY"/>
 *     &lt;enumeration value="SIN"/>
 *     &lt;enumeration value="SKN"/>
 *     &lt;enumeration value="SLE"/>
 *     &lt;enumeration value="SLO"/>
 *     &lt;enumeration value="SMR"/>
 *     &lt;enumeration value="SOL"/>
 *     &lt;enumeration value="SOM"/>
 *     &lt;enumeration value="SRB"/>
 *     &lt;enumeration value="SRI"/>
 *     &lt;enumeration value="STP"/>
 *     &lt;enumeration value="SUD"/>
 *     &lt;enumeration value="SUI"/>
 *     &lt;enumeration value="SUR"/>
 *     &lt;enumeration value="SVK"/>
 *     &lt;enumeration value="SWE"/>
 *     &lt;enumeration value="SWZ"/>
 *     &lt;enumeration value="SYR"/>
 *     &lt;enumeration value="TAH"/>
 *     &lt;enumeration value="TAI"/>
 *     &lt;enumeration value="TAN"/>
 *     &lt;enumeration value="TCH"/>
 *     &lt;enumeration value="TGA"/>
 *     &lt;enumeration value="THA"/>
 *     &lt;enumeration value="TJK"/>
 *     &lt;enumeration value="TKM"/>
 *     &lt;enumeration value="TKS"/>
 *     &lt;enumeration value="TLS"/>
 *     &lt;enumeration value="TOG"/>
 *     &lt;enumeration value="TPE"/>
 *     &lt;enumeration value="TRI"/>
 *     &lt;enumeration value="TUN"/>
 *     &lt;enumeration value="TUR"/>
 *     &lt;enumeration value="TUV"/>
 *     &lt;enumeration value="UAE"/>
 *     &lt;enumeration value="UGA"/>
 *     &lt;enumeration value="UKR"/>
 *     &lt;enumeration value="URS"/>
 *     &lt;enumeration value="URU"/>
 *     &lt;enumeration value="USA"/>
 *     &lt;enumeration value="UZB"/>
 *     &lt;enumeration value="VAN"/>
 *     &lt;enumeration value="VEN"/>
 *     &lt;enumeration value="VIE"/>
 *     &lt;enumeration value="VIN"/>
 *     &lt;enumeration value="YEM"/>
 *     &lt;enumeration value="YUG"/>
 *     &lt;enumeration value="ZAI"/>
 *     &lt;enumeration value="ZAM"/>
 *     &lt;enumeration value="ZIM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IFNationCode")
@XmlEnum
public enum IFNationCode {


    /**
     * Afghanistan
     * 
     */
    AFG,

    /**
     * Netherlands Antilles
     * 
     */
    AHO,

    /**
     * Albania
     * 
     */
    ALB,

    /**
     * Algeria
     * 
     */
    ALG,

    /**
     * Anguilla
     * 
     */
    ANA,

    /**
     * Andorra
     * 
     */
    AND,

    /**
     * Angola
     * 
     */
    ANG,

    /**
     * Antigua
     * 
     */
    ANT,

    /**
     * Argentina
     * 
     */
    ARG,

    /**
     * Armenia
     * 
     */
    ARM,

    /**
     * Aruba
     * 
     */
    ARU,

    /**
     * American Samoa
     * 
     */
    ASA,

    /**
     * Australia
     * 
     */
    AUS,

    /**
     * Austria
     * 
     */
    AUT,

    /**
     * Azerbaijan
     * 
     */
    AZE,

    /**
     * Bahamas
     * 
     */
    BAH,

    /**
     * Bangladesh
     * 
     */
    BAN,

    /**
     * Barbados
     * 
     */
    BAR,

    /**
     * Burundi
     * 
     */
    BDI,

    /**
     * Belgium
     * 
     */
    BEL,

    /**
     * Benin
     * 
     */
    BEN,

    /**
     * Bermuda
     * 
     */
    BER,

    /**
     * Bhutan
     * 
     */
    BHU,

    /**
     * Bosnia & Herzegovina
     * 
     */
    BIH,

    /**
     * BURMA
     * 
     */
    BIR,

    /**
     * Belize
     * 
     */
    BIZ,

    /**
     * Belarus
     * 
     */
    BLR,

    /**
     * Bolivia
     * 
     */
    BOL,

    /**
     * Botswana
     * 
     */
    BOT,

    /**
     * Brazil
     * 
     */
    BRA,

    /**
     * Bahrain
     * 
     */
    BRN,

    /**
     * Brunei
     * 
     */
    BRU,

    /**
     * Bulgaria
     * 
     */
    BUL,

    /**
     * Burkina Faso
     * 
     */
    BUR,

    /**
     * BRITISH WEST INDIES
     * 
     */
    BWI,

    /**
     * Central Africa
     * 
     */
    CAF,

    /**
     * New Caledonia
     * 
     */
    CAL,

    /**
     * Cambodia
     * 
     */
    CAM,

    /**
     * Canada
     * 
     */
    CAN,

    /**
     * Cayman Islands
     * 
     */
    CAY,

    /**
     * Congo
     * 
     */
    CGO,

    /**
     * Chad
     * 
     */
    CHA,

    /**
     * Chile
     * 
     */
    CHI,

    /**
     * China, PR
     * 
     */
    CHN,

    /**
     * Ivory Coast
     * 
     */
    CIV,

    /**
     * Cameroon
     * 
     */
    CMR,

    /**
     * DR Congo
     * 
     */
    COD,

    /**
     * Cook Islands
     * 
     */
    COK,

    /**
     * Colombia
     * 
     */
    COL,

    /**
     * Comoros
     * 
     */
    COM,

    /**
     * Cape Verde
     * 
     */
    CPV,

    /**
     * Costa Rica
     * 
     */
    CRC,

    /**
     * Croatia
     * 
     */
    CRO,

    /**
     * Cuba
     * 
     */
    CUB,

    /**
     * Curacao
     * 
     */
    CUR,

    /**
     * Cyprus
     * 
     */
    CYP,

    /**
     * Czech Republic
     * 
     */
    CZE,

    /**
     * Denmark
     * 
     */
    DEN,

    /**
     * Djibouti
     * 
     */
    DJI,

    /**
     * Dominica
     * 
     */
    DMA,

    /**
     * Dominican Republic
     * 
     */
    DOM,

    /**
     * Ecuador
     * 
     */
    ECU,

    /**
     * Egypt
     * 
     */
    EGY,

    /**
     * Eritrea
     * 
     */
    ERI,

    /**
     * El Salvador
     * 
     */
    ESA,

    /**
     * Spain
     * 
     */
    ESP,

    /**
     * Estonia
     * 
     */
    EST,

    /**
     * Ethiopia
     * 
     */
    ETH,

    /**
     * EQUIPE UNIFIÉE ALLEMANDE
     * 
     */
    EUA,

    /**
     * Unified Team
     * 
     */
    EUN,

    /**
     * Faroe Islands
     * 
     */
    FAR,

    /**
     * French Guiana
     * 
     */
    FGU,

    /**
     * Fiji
     * 
     */
    FIJ,

    /**
     * Finland
     * 
     */
    FIN,

    /**
     * France
     * 
     */
    FRA,

    /**
     * Federal Republic of Germany (1950)
     * 
     */
    FRG,

    /**
     * Micronesia
     * 
     */
    FSM,

    /**
     * Gabon
     * 
     */
    GAB,

    /**
     * Gambia
     * 
     */
    GAM,

    /**
     * Great Britain
     * 
     */
    GBR,

    /**
     * Guinea-bissau
     * 
     */
    GBS,

    /**
     * German Democratic Republic (1955)
     * 
     */
    GDR,

    /**
     * Georgia
     * 
     */
    GEO,

    /**
     * Equatorial Guinea
     * 
     */
    GEQ,

    /**
     * Germany
     * 
     */
    GER,

    /**
     * Ghana
     * 
     */
    GHA,

    /**
     * Gibraltar
     * 
     */
    GIB,

    /**
     * Greece
     * 
     */
    GRE,

    /**
     * Grenada
     * 
     */
    GRN,

    /**
     * Guatemala
     * 
     */
    GUA,

    /**
     * Guadeloupe
     * 
     */
    GUD,

    /**
     * Guinea
     * 
     */
    GUI,

    /**
     * Guam
     * 
     */
    GUM,

    /**
     * Guyana
     * 
     */
    GUY,

    /**
     * Haiti
     * 
     */
    HAI,

    /**
     * Hong Kong
     * 
     */
    HKG,

    /**
     * Honduras
     * 
     */
    HON,

    /**
     * Hungary
     * 
     */
    HUN,

    /**
     * Indonesia
     * 
     */
    INA,

    /**
     * India
     * 
     */
    IND,

    /**
     * Independent Olympic Athlete
     * 
     */
    IOA,

    /**
     * I.R. Iran
     * 
     */
    IRI,

    /**
     * Ireland
     * 
     */
    IRL,

    /**
     * Iraq
     * 
     */
    IRQ,

    /**
     * Iceland
     * 
     */
    ISL,

    /**
     * Israel
     * 
     */
    ISR,

    /**
     * US Virgin Islands
     * 
     */
    ISV,

    /**
     * Italy
     * 
     */
    ITA,

    /**
     * British Virgin Islands
     * 
     */
    IVB,

    /**
     * Jamaica
     * 
     */
    JAM,

    /**
     * Jordan
     * 
     */
    JOR,

    /**
     * Japan
     * 
     */
    JPN,

    /**
     * Kazakhstan
     * 
     */
    KAZ,

    /**
     * Kenya
     * 
     */
    KEN,

    /**
     * Kyrgyzstan
     * 
     */
    KGZ,

    /**
     * Kiribati
     * 
     */
    KIR,

    /**
     * Korea
     * 
     */
    KOR,

    /**
     * Kosovo
     * 
     */
    KOS,

    /**
     * Saudi Arabia
     * 
     */
    KSA,

    /**
     * Kuwait
     * 
     */
    KUW,

    /**
     * Lao P.d.r.
     * 
     */
    LAO,

    /**
     * Latvia
     * 
     */
    LAT,

    /**
     * Libya
     * 
     */
    LBA,

    /**
     * Liberia
     * 
     */
    LBR,

    /**
     * St Lucia
     * 
     */
    LCA,

    /**
     * Lesotho
     * 
     */
    LES,

    /**
     * Lebanon
     * 
     */
    LIB,

    /**
     * Liechtenstein
     * 
     */
    LIE,

    /**
     * Lithuania
     * 
     */
    LTU,

    /**
     * Luxembourg
     * 
     */
    LUX,

    /**
     * Macau
     * 
     */
    MAC,

    /**
     * Madagascar
     * 
     */
    MAD,

    /**
     * Morocco
     * 
     */
    MAR,

    /**
     * Malaysia
     * 
     */
    MAS,

    /**
     * Malawi
     * 
     */
    MAW,

    /**
     * Moldova
     * 
     */
    MDA,

    /**
     * Maldives
     * 
     */
    MDV,

    /**
     * Mexico
     * 
     */
    MEX,

    /**
     * Mongolia
     * 
     */
    MGL,

    /**
     * Marshall Islands
     * 
     */
    MHL,

    /**
     * Macedonia (FYRO)
     * 
     */
    MKD,

    /**
     * Mali
     * 
     */
    MLI,

    /**
     * Malta
     * 
     */
    MLT,

    /**
     * Montenegro
     * 
     */
    MNE,

    /**
     * Montserrat
     * 
     */
    MNT,

    /**
     * Monaco
     * 
     */
    MON,

    /**
     * Mozambique
     * 
     */
    MOZ,

    /**
     * Mauritius
     * 
     */
    MRI,

    /**
     * Martinique
     * 
     */
    MRN,

    /**
     * Mauritania
     * 
     */
    MTN,

    /**
     * Myanmar
     * 
     */
    MYA,

    /**
     * Namibia
     * 
     */
    NAM,

    /**
     * Nicaragua
     * 
     */
    NCA,

    /**
     * Netherlands
     * 
     */
    NED,

    /**
     * Nepal
     * 
     */
    NEP,

    /**
     * Nigeria
     * 
     */
    NGR,

    /**
     * Niger
     * 
     */
    NIG,

    /**
     * Northern Mariana Islands
     * 
     */
    NMI,

    /**
     * Norway
     * 
     */
    NOR,

    /**
     * Nauru
     * 
     */
    NRU,

    /**
     * New Zealand
     * 
     */
    NZL,

    /**
     * Oman
     * 
     */
    OMA,

    /**
     * Pakistan
     * 
     */
    PAK,

    /**
     * Panama
     * 
     */
    PAN,

    /**
     * Paraguay
     * 
     */
    PAR,

    /**
     * Peru
     * 
     */
    PER,

    /**
     * Philippines
     * 
     */
    PHI,

    /**
     * Palestine
     * 
     */
    PLE,

    /**
     * Palau
     * 
     */
    PLW,

    /**
     * Papua New Guinea
     * 
     */
    PNG,

    /**
     * Poland
     * 
     */
    POL,

    /**
     * Portugal
     * 
     */
    POR,

    /**
     * Dpr Korea
     * 
     */
    PRK,

    /**
     * Puerto Rico
     * 
     */
    PUR,

    /**
     * Qatar
     * 
     */
    QAT,

    /**
     * Reunion
     * 
     */
    REU,

    /**
     * RHODÉSIE
     * 
     */
    RHO,

    /**
     * ROMANIA
     * 
     */
    ROM,

    /**
     * Romania
     * 
     */
    ROU,

    /**
     * South Africa
     * 
     */
    RSA,

    /**
     * Russia
     * 
     */
    RUS,

    /**
     * Rwanda
     * 
     */
    RWA,

    /**
     * Samoa
     * 
     */
    SAM,

    /**
     * Senegal
     * 
     */
    SEN,

    /**
     * Seychelles
     * 
     */
    SEY,

    /**
     * Singapore
     * 
     */
    SGP,

    /**
     * St Kitts
     * 
     */
    SKN,

    /**
     * Sierra Leone
     * 
     */
    SLE,

    /**
     * Slovenia
     * 
     */
    SLO,

    /**
     * San Marino
     * 
     */
    SMR,

    /**
     * Solomon Islands
     * 
     */
    SOL,

    /**
     * Somalia
     * 
     */
    SOM,

    /**
     * Serbia
     * 
     */
    SRB,

    /**
     * Sri Lanka
     * 
     */
    SRI,

    /**
     * Sao Tome And Principe
     * 
     */
    STP,

    /**
     * Sudan
     * 
     */
    SUD,

    /**
     * Switzerland
     * 
     */
    SUI,

    /**
     * Suriname
     * 
     */
    SUR,

    /**
     * Slovakia
     * 
     */
    SVK,

    /**
     * Sweden
     * 
     */
    SWE,

    /**
     * Swaziland
     * 
     */
    SWZ,

    /**
     * Syria
     * 
     */
    SYR,

    /**
     * Tahiti
     * 
     */
    TAH,

    /**
     * Taiwan
     * 
     */
    TAI,

    /**
     * Tanzania
     * 
     */
    TAN,

    /**
     * CZECHOSLOVAKIA
     * 
     */
    TCH,

    /**
     * Tonga
     * 
     */
    TGA,

    /**
     * Thailand
     * 
     */
    THA,

    /**
     * Tajikistan
     * 
     */
    TJK,

    /**
     * Turkmenistan
     * 
     */
    TKM,

    /**
     * Turks & Caicos Islands
     * 
     */
    TKS,

    /**
     * Timor Leste
     * 
     */
    TLS,

    /**
     * Togo
     * 
     */
    TOG,

    /**
     * Chinese Taipei
     * 
     */
    TPE,

    /**
     * Trinidad And Tobago
     * 
     */
    TTO,

    /**
     * Tunisia
     * 
     */
    TUN,

    /**
     * Turkey
     * 
     */
    TUR,

    /**
     * Tuvalu
     * 
     */
    TUV,

    /**
     * United Arab Emirates
     * 
     */
    UAE,

    /**
     * Uganda
     * 
     */
    UGA,

    /**
     * Ukraine
     * 
     */
    UKR,

    /**
     * USSR
     * 
     */
    URS,

    /**
     * Uruguay
     * 
     */
    URU,

    /**
     * USA
     * 
     */
    USA,

    /**
     * Uzbekistan
     * 
     */
    UZB,

    /**
     * Vanuatu
     * 
     */
    VAN,

    /**
     * Venezuela
     * 
     */
    VEN,

    /**
     * Vietnam
     * 
     */
    VIE,

    /**
     * St Vincent
     * 
     */
    VIN,

    /**
     * Yemen
     * 
     */
    YEM,

    /**
     * Yugoslavia
     * 
     */
    YUG,

    /**
     * Zaire
     * 
     */
    ZAI,

    /**
     * Zambia
     * 
     */
    ZAM,

    /**
     * Zimbabwe
     * 
     */
    ZIM;

    public String value() {
        return name();
    }

    public static IFNationCode fromValue(String v) {
        return valueOf(v);
    }

}
