//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sap.sailing.xrr.resultimport.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SailingXRR_QNAME = new QName("", "SailingXRR");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sap.sailing.xrr.resultimport.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegattaResults }
     * 
     */
    public RegattaResults createRegattaResults() {
        return new RegattaResults();
    }

    /**
     * Create an instance of {@link EventRef }
     * 
     */
    public EventRef createEventRef() {
        return new EventRef();
    }

    /**
     * Create an instance of {@link Boat }
     * 
     */
    public Boat createBoat() {
        return new Boat();
    }

    /**
     * Create an instance of {@link SeriesResult }
     * 
     */
    public SeriesResult createSeriesResult() {
        return new SeriesResult();
    }

    /**
     * Create an instance of {@link RaceResult }
     * 
     */
    public RaceResult createRaceResult() {
        return new RaceResult();
    }

    /**
     * Create an instance of {@link TRResult }
     * 
     */
    public TRResult createTRResult() {
        return new TRResult();
    }

    /**
     * Create an instance of {@link Crew }
     * 
     */
    public Crew createCrew() {
        return new Crew();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Race }
     * 
     */
    public Race createRace() {
        return new Race();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link Division }
     * 
     */
    public Division createDivision() {
        return new Division();
    }

    /**
     * Create an instance of {@link RegattaSeriesResult }
     * 
     */
    public RegattaSeriesResult createRegattaSeriesResult() {
        return new RegattaSeriesResult();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegattaResults }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SailingXRR")
    public JAXBElement<RegattaResults> createSailingXRR(RegattaResults value) {
        return new JAXBElement<RegattaResults>(_SailingXRR_QNAME, RegattaResults.class, null, value);
    }

}
