//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="PersonID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IFPersonID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FamilyName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NOC" type="{}IFNationCode" />
 *       &lt;attribute name="Gender" type="{}PersonGender" />
 *       &lt;attribute name="ClassificationGroup" type="{}IFCfcnGroup" />
 *       &lt;attribute name="ClassificationStatus" type="{}IFCfcnStatus" />
 *       &lt;attribute name="ClassificationExpiry" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person")
public class Person {

    @XmlAttribute(name = "PersonID", required = true)
    protected String personID;
    @XmlAttribute(name = "IFPersonID", required = true)
    protected String ifPersonID;
    @XmlAttribute(name = "FamilyName", required = true)
    protected String familyName;
    @XmlAttribute(name = "GivenName")
    protected String givenName;
    @XmlAttribute(name = "NOC")
    protected IFNationCode noc;
    @XmlAttribute(name = "Gender")
    protected PersonGender gender;
    @XmlAttribute(name = "ClassificationGroup")
    protected String classificationGroup;
    @XmlAttribute(name = "ClassificationStatus")
    protected IFCfcnStatus classificationStatus;
    @XmlAttribute(name = "ClassificationExpiry")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar classificationExpiry;

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonID(String value) {
        this.personID = value;
    }

    /**
     * Gets the value of the ifPersonID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIFPersonID() {
        return ifPersonID;
    }

    /**
     * Sets the value of the ifPersonID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIFPersonID(String value) {
        this.ifPersonID = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the noc property.
     * 
     * @return
     *     possible object is
     *     {@link IFNationCode }
     *     
     */
    public IFNationCode getNOC() {
        return noc;
    }

    /**
     * Sets the value of the noc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFNationCode }
     *     
     */
    public void setNOC(IFNationCode value) {
        this.noc = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link PersonGender }
     *     
     */
    public PersonGender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonGender }
     *     
     */
    public void setGender(PersonGender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the classificationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationGroup() {
        return classificationGroup;
    }

    /**
     * Sets the value of the classificationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationGroup(String value) {
        this.classificationGroup = value;
    }

    /**
     * Gets the value of the classificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link IFCfcnStatus }
     *     
     */
    public IFCfcnStatus getClassificationStatus() {
        return classificationStatus;
    }

    /**
     * Sets the value of the classificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFCfcnStatus }
     *     
     */
    public void setClassificationStatus(IFCfcnStatus value) {
        this.classificationStatus = value;
    }

    /**
     * Gets the value of the classificationExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClassificationExpiry() {
        return classificationExpiry;
    }

    /**
     * Sets the value of the classificationExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClassificationExpiry(XMLGregorianCalendar value) {
        this.classificationExpiry = value;
    }

}
