//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RaceResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RaceResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Crew" type="{}Crew" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="RaceID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TeamID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BoatID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RacePoints" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RaceRank" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="Discard" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ScoreCode" type="{}IFBoatStatus" />
 *       &lt;attribute name="Entry" type="{}MatchRaceEntry" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RaceResult", propOrder = {
    "crew"
})
public class RaceResult {

    @XmlElement(name = "Crew")
    protected List<Crew> crew;
    @XmlAttribute(name = "RaceID", required = true)
    protected String raceID;
    @XmlAttribute(name = "TeamID")
    protected String teamID;
    @XmlAttribute(name = "BoatID")
    protected String boatID;
    @XmlAttribute(name = "RacePoints", required = true)
    protected BigDecimal racePoints;
    @XmlAttribute(name = "RaceRank")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger raceRank;
    @XmlAttribute(name = "Discard")
    protected Boolean discard;
    @XmlAttribute(name = "ScoreCode")
    protected IFBoatStatus scoreCode;
    @XmlAttribute(name = "Entry")
    protected MatchRaceEntry entry;

    /**
     * Gets the value of the crew property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crew property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrew().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Crew }
     * 
     * 
     */
    public List<Crew> getCrew() {
        if (crew == null) {
            crew = new ArrayList<Crew>();
        }
        return this.crew;
    }

    /**
     * Gets the value of the raceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceID() {
        return raceID;
    }

    /**
     * Sets the value of the raceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceID(String value) {
        this.raceID = value;
    }

    /**
     * Gets the value of the teamID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamID() {
        return teamID;
    }

    /**
     * Sets the value of the teamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamID(String value) {
        this.teamID = value;
    }

    /**
     * Gets the value of the boatID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoatID() {
        return boatID;
    }

    /**
     * Sets the value of the boatID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoatID(String value) {
        this.boatID = value;
    }

    /**
     * Gets the value of the racePoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRacePoints() {
        return racePoints;
    }

    /**
     * Sets the value of the racePoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRacePoints(BigDecimal value) {
        this.racePoints = value;
    }

    /**
     * Gets the value of the raceRank property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRaceRank() {
        return raceRank;
    }

    /**
     * Sets the value of the raceRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRaceRank(BigInteger value) {
        this.raceRank = value;
    }

    /**
     * Gets the value of the discard property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDiscard() {
        if (discard == null) {
            return false;
        } else {
            return discard;
        }
    }

    /**
     * Sets the value of the discard property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiscard(Boolean value) {
        this.discard = value;
    }

    /**
     * Gets the value of the scoreCode property.
     * 
     * @return
     *     possible object is
     *     {@link IFBoatStatus }
     *     
     */
    public IFBoatStatus getScoreCode() {
        return scoreCode;
    }

    /**
     * Sets the value of the scoreCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFBoatStatus }
     *     
     */
    public void setScoreCode(IFBoatStatus value) {
        this.scoreCode = value;
    }

    /**
     * Gets the value of the entry property.
     * 
     * @return
     *     possible object is
     *     {@link MatchRaceEntry }
     *     
     */
    public MatchRaceEntry getEntry() {
        return entry;
    }

    /**
     * Sets the value of the entry property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchRaceEntry }
     *     
     */
    public void setEntry(MatchRaceEntry value) {
        this.entry = value;
    }

}
