//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:56:46 PM CET 
//


package com.sap.sailing.xrr.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Team complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Team">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Crew" type="{}Crew" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TeamID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BoatID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NOC" type="{}IFNationCode" />
 *       &lt;attribute name="TeamName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Gender" type="{}EventGender" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Team", propOrder = {
    "crew"
})
public class Team {

    @XmlElement(name = "Crew")
    protected List<Crew> crew;
    @XmlAttribute(name = "TeamID", required = true)
    protected String teamID;
    @XmlAttribute(name = "BoatID")
    protected String boatID;
    @XmlAttribute(name = "NOC")
    protected IFNationCode noc;
    @XmlAttribute(name = "TeamName")
    protected String teamName;
    @XmlAttribute(name = "Gender")
    protected EventGender gender;

    /**
     * Gets the value of the crew property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crew property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrew().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Crew }
     * 
     * 
     */
    public List<Crew> getCrew() {
        if (crew == null) {
            crew = new ArrayList<Crew>();
        }
        return this.crew;
    }

    /**
     * Gets the value of the teamID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamID() {
        return teamID;
    }

    /**
     * Sets the value of the teamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamID(String value) {
        this.teamID = value;
    }

    /**
     * Gets the value of the boatID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoatID() {
        return boatID;
    }

    /**
     * Sets the value of the boatID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoatID(String value) {
        this.boatID = value;
    }

    /**
     * Gets the value of the noc property.
     * 
     * @return
     *     possible object is
     *     {@link IFNationCode }
     *     
     */
    public IFNationCode getNOC() {
        return noc;
    }

    /**
     * Sets the value of the noc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFNationCode }
     *     
     */
    public void setNOC(IFNationCode value) {
        this.noc = value;
    }

    /**
     * Gets the value of the teamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * Sets the value of the teamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamName(String value) {
        this.teamName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link EventGender }
     *     
     */
    public EventGender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventGender }
     *     
     */
    public void setGender(EventGender value) {
        this.gender = value;
    }

}
