#!/bin/bash

# Script to deploy on an instance that has an ephemeral volume as /dev/nvme0n1 (adjust env var PARTITION if different)
# Ensures the partition is xfs-formatted, any existing partition contents will be overwritten if formatted otherwise.
# An existing xfs partition will be left alone.
EPHEMERAL_NVME=$( for i in $(lsblk | grep -o "nvme[0-9][0-9]\?n[0-9]" | sort -u); do /sbin/ebsnvme-id -u "/dev/$i" >> /dev/null;  if [[ $? -ne 0 ]]; then echo "$i" ; fi; done 2>/dev/null  | head -n 1)
if [[ -z "$EPHEMERAL_NVME"  ]]; then
    exit 1
fi
PARTITION=/dev/${EPHEMERAL_NVME}
FSTYPE=$(blkid -p $PARTITION -s TYPE -o value)
if [ "$FSTYPE" = "" ]; then
  echo FSTYPE was empty, creating swap partition
  mkswap $PARTITION
  swapon -a $PARTITION
else
  echo FSTYPE was "$FSTYPE", not touching
fi
