#!/bin/bash

# Purpose: Deployed in a file named "post-receive", in the hooks dir of a bare git repo. Upon push completion, this script runs and
# triggers an update to instances in the region with a specified tag. A command is ran in the repo 
# after the merge completes. The user, in which the bare repo and hook are installed, must have aws credentials, that
# don't need mfa. (These may need to be installed manually -- within the correct user -- if starting from a clean instance.)

DISPOSABLE_TAG="DisposableProxy"
CENTRAL_TAG="CentralReverseProxy"
DIR="/etc/httpd"
COMMAND="sudo service httpd reload"
MAIN_BRANCH_NAME="main"
DISPOSABLE_BRANCH_NAME="disposable"
CENTRAL_BRANCH_NAME="central"
CHECKED_OUT_WORKSPACE_NAME="checked-out" # Assumes it is in the root user.
sync_repo() {
            #$1 tag key to use
            #$2 branch to check out
            # Gets all public ips for the instances with the chosen tag and iterates over the IPs.
            for IP in $(aws ec2 describe-instances --filters Name=tag-key,Values="${1}" | jq -r '.Reservations[].Instances[].PublicIpAddress'); do
                # strictHostKey... means no authenticity check. The sync-repo... script must be installed in the root user's home.
                echo $IP
                ssh -o "StrictHostKeyChecking=no" root@${IP} "cd ~ && sync-repo-and-execute-cmd.sh '${DIR}' '${COMMAND}' '${2}'";
            done;
}
merge_main_into_branch() {
        #$1 branch name. Assumes you are in the git repo.
        git checkout "${1}"
        git pull
        echo "merging ${MAIN_BRANCH_NAME} into ${1}"
        git merge ${MAIN_BRANCH_NAME}
        git push
}
while read oldrev newrev refname; do   # These vars are passed on stdin to this hook.
    # Check if the update is on a branch
    if [[ $refname == "refs/heads/"* ]]; then
        branch_name=$(echo $refname | sed "s|refs/heads/\(.*\)$|\1|")
        echo "Update on branch: $branch_name"
        if [[ "$branch_name" == "$DISPOSABLE_BRANCH_NAME" ]]; then
            echo "All the disposables pull the disposable branch"
            sync_repo "${DISPOSABLE_TAG}" "${DISPOSABLE_BRANCH_NAME}"
        elif [[ "$branch_name" == "$CENTRAL_BRANCH_NAME" ]]; then
            echo "The central pulls the central branch"
            sync_repo "${CENTRAL_TAG}" "${CENTRAL_BRANCH_NAME}"
        elif [[ "$branch_name" == "$MAIN_BRANCH_NAME" ]]; then
                cd ~
                unset GIT_DIR
                cd ${CHECKED_OUT_WORKSPACE_NAME}
                # get the latest main
                git checkout ${MAIN_BRANCH_NAME}
                git pull
                # get the latest diposable branch and merge in changes
                merge_main_into_branch "$DISPOSABLE_BRANCH_NAME"
                # get the latest central branch and merge in changes
                merge_main_into_branch "$CENTRAL_BRANCH_NAME"
                git checkout ${MAIN_BRANCH_NAME}
        fi
    fi
done