// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/igtimi/IgtimiTimeSync.proto
// Protobuf Java Version: 4.28.3

package com.igtimi.timesync.proto;

/**
 * Protobuf type {@code com.igtimi.NTPResponse}
 */
public final class NTPResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.igtimi.NTPResponse)
    NTPResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      NTPResponse.class.getName());
  }
  // Use NTPResponse.newBuilder() to construct.
  private NTPResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NTPResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_NTPResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_NTPResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.igtimi.timesync.proto.NTPResponse.class, com.igtimi.timesync.proto.NTPResponse.Builder.class);
  }

  public static final int LEAP_INDICATOR_FIELD_NUMBER = 1;
  private int leapIndicator_ = 0;
  /**
   * <code>uint32 leap_indicator = 1 [json_name = "leapIndicator"];</code>
   * @return The leapIndicator.
   */
  @java.lang.Override
  public int getLeapIndicator() {
    return leapIndicator_;
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private int version_ = 0;
  /**
   * <code>uint32 version = 2 [json_name = "version"];</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int MODE_FIELD_NUMBER = 3;
  private int mode_ = 0;
  /**
   * <code>uint32 mode = 3 [json_name = "mode"];</code>
   * @return The mode.
   */
  @java.lang.Override
  public int getMode() {
    return mode_;
  }

  public static final int STRATUM_FIELD_NUMBER = 4;
  private int stratum_ = 0;
  /**
   * <code>uint32 stratum = 4 [json_name = "stratum"];</code>
   * @return The stratum.
   */
  @java.lang.Override
  public int getStratum() {
    return stratum_;
  }

  public static final int POLL_INTERVAL_FIELD_NUMBER = 5;
  private int pollInterval_ = 0;
  /**
   * <code>uint32 poll_interval = 5 [json_name = "pollInterval"];</code>
   * @return The pollInterval.
   */
  @java.lang.Override
  public int getPollInterval() {
    return pollInterval_;
  }

  public static final int PRECISION_FIELD_NUMBER = 6;
  private int precision_ = 0;
  /**
   * <code>int32 precision = 6 [json_name = "precision"];</code>
   * @return The precision.
   */
  @java.lang.Override
  public int getPrecision() {
    return precision_;
  }

  public static final int ROOT_DELAY_FIELD_NUMBER = 7;
  private double rootDelay_ = 0D;
  /**
   * <code>double root_delay = 7 [json_name = "rootDelay"];</code>
   * @return The rootDelay.
   */
  @java.lang.Override
  public double getRootDelay() {
    return rootDelay_;
  }

  public static final int ROOT_DISPERSION_FIELD_NUMBER = 8;
  private double rootDispersion_ = 0D;
  /**
   * <code>double root_dispersion = 8 [json_name = "rootDispersion"];</code>
   * @return The rootDispersion.
   */
  @java.lang.Override
  public double getRootDispersion() {
    return rootDispersion_;
  }

  public static final int REFERENCE_TIMESTAMP_FIELD_NUMBER = 9;
  private double referenceTimestamp_ = 0D;
  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double reference_timestamp = 9 [json_name = "referenceTimestamp"];</code>
   * @return The referenceTimestamp.
   */
  @java.lang.Override
  public double getReferenceTimestamp() {
    return referenceTimestamp_;
  }

  public static final int ORIGINATE_TIMESTAMP_FIELD_NUMBER = 10;
  private double originateTimestamp_ = 0D;
  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double originate_timestamp = 10 [json_name = "originateTimestamp"];</code>
   * @return The originateTimestamp.
   */
  @java.lang.Override
  public double getOriginateTimestamp() {
    return originateTimestamp_;
  }

  public static final int RECEIVE_TIMESTAMP_FIELD_NUMBER = 11;
  private double receiveTimestamp_ = 0D;
  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double receive_timestamp = 11 [json_name = "receiveTimestamp"];</code>
   * @return The receiveTimestamp.
   */
  @java.lang.Override
  public double getReceiveTimestamp() {
    return receiveTimestamp_;
  }

  public static final int TRANSMIT_TIMESTAMP_FIELD_NUMBER = 12;
  private double transmitTimestamp_ = 0D;
  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double transmit_timestamp = 12 [json_name = "transmitTimestamp"];</code>
   * @return The transmitTimestamp.
   */
  @java.lang.Override
  public double getTransmitTimestamp() {
    return transmitTimestamp_;
  }

  public static final int REFERENCE_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER = 13;
  private long referenceTimestampMsSince1970_ = 0L;
  /**
   * <pre>
   * These fields are not part of the standard message
   * </pre>
   *
   * <code>uint64 reference_timestamp_ms_since_1970 = 13 [json_name = "referenceTimestampMs1970"];</code>
   * @return The referenceTimestampMsSince1970.
   */
  @java.lang.Override
  public long getReferenceTimestampMsSince1970() {
    return referenceTimestampMsSince1970_;
  }

  public static final int ORIGINATE_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER = 14;
  private long originateTimestampMsSince1970_ = 0L;
  /**
   * <pre>
   * in ms since 1970
   * </pre>
   *
   * <code>uint64 originate_timestamp_ms_since_1970 = 14 [json_name = "originateTimestampMs1970"];</code>
   * @return The originateTimestampMsSince1970.
   */
  @java.lang.Override
  public long getOriginateTimestampMsSince1970() {
    return originateTimestampMsSince1970_;
  }

  public static final int RECEIVE_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER = 15;
  private long receiveTimestampMsSince1970_ = 0L;
  /**
   * <pre>
   * in ms since 1970
   * </pre>
   *
   * <code>uint64 receive_timestamp_ms_since_1970 = 15 [json_name = "receiveTimestampMs1970"];</code>
   * @return The receiveTimestampMsSince1970.
   */
  @java.lang.Override
  public long getReceiveTimestampMsSince1970() {
    return receiveTimestampMsSince1970_;
  }

  public static final int TRANSMIT_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER = 16;
  private long transmitTimestampMsSince1970_ = 0L;
  /**
   * <pre>
   * in ms since 1970
   * </pre>
   *
   * <code>uint64 transmit_timestamp_ms_since_1970 = 16 [json_name = "transmitTimestampMs1970"];</code>
   * @return The transmitTimestampMsSince1970.
   */
  @java.lang.Override
  public long getTransmitTimestampMsSince1970() {
    return transmitTimestampMsSince1970_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (leapIndicator_ != 0) {
      output.writeUInt32(1, leapIndicator_);
    }
    if (version_ != 0) {
      output.writeUInt32(2, version_);
    }
    if (mode_ != 0) {
      output.writeUInt32(3, mode_);
    }
    if (stratum_ != 0) {
      output.writeUInt32(4, stratum_);
    }
    if (pollInterval_ != 0) {
      output.writeUInt32(5, pollInterval_);
    }
    if (precision_ != 0) {
      output.writeInt32(6, precision_);
    }
    if (java.lang.Double.doubleToRawLongBits(rootDelay_) != 0) {
      output.writeDouble(7, rootDelay_);
    }
    if (java.lang.Double.doubleToRawLongBits(rootDispersion_) != 0) {
      output.writeDouble(8, rootDispersion_);
    }
    if (java.lang.Double.doubleToRawLongBits(referenceTimestamp_) != 0) {
      output.writeDouble(9, referenceTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(originateTimestamp_) != 0) {
      output.writeDouble(10, originateTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(receiveTimestamp_) != 0) {
      output.writeDouble(11, receiveTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(transmitTimestamp_) != 0) {
      output.writeDouble(12, transmitTimestamp_);
    }
    if (referenceTimestampMsSince1970_ != 0L) {
      output.writeUInt64(13, referenceTimestampMsSince1970_);
    }
    if (originateTimestampMsSince1970_ != 0L) {
      output.writeUInt64(14, originateTimestampMsSince1970_);
    }
    if (receiveTimestampMsSince1970_ != 0L) {
      output.writeUInt64(15, receiveTimestampMsSince1970_);
    }
    if (transmitTimestampMsSince1970_ != 0L) {
      output.writeUInt64(16, transmitTimestampMsSince1970_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (leapIndicator_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, leapIndicator_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, version_);
    }
    if (mode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, mode_);
    }
    if (stratum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, stratum_);
    }
    if (pollInterval_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, pollInterval_);
    }
    if (precision_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, precision_);
    }
    if (java.lang.Double.doubleToRawLongBits(rootDelay_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, rootDelay_);
    }
    if (java.lang.Double.doubleToRawLongBits(rootDispersion_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, rootDispersion_);
    }
    if (java.lang.Double.doubleToRawLongBits(referenceTimestamp_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, referenceTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(originateTimestamp_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, originateTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(receiveTimestamp_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, receiveTimestamp_);
    }
    if (java.lang.Double.doubleToRawLongBits(transmitTimestamp_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, transmitTimestamp_);
    }
    if (referenceTimestampMsSince1970_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, referenceTimestampMsSince1970_);
    }
    if (originateTimestampMsSince1970_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(14, originateTimestampMsSince1970_);
    }
    if (receiveTimestampMsSince1970_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(15, receiveTimestampMsSince1970_);
    }
    if (transmitTimestampMsSince1970_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(16, transmitTimestampMsSince1970_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.igtimi.timesync.proto.NTPResponse)) {
      return super.equals(obj);
    }
    com.igtimi.timesync.proto.NTPResponse other = (com.igtimi.timesync.proto.NTPResponse) obj;

    if (getLeapIndicator()
        != other.getLeapIndicator()) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (getMode()
        != other.getMode()) return false;
    if (getStratum()
        != other.getStratum()) return false;
    if (getPollInterval()
        != other.getPollInterval()) return false;
    if (getPrecision()
        != other.getPrecision()) return false;
    if (java.lang.Double.doubleToLongBits(getRootDelay())
        != java.lang.Double.doubleToLongBits(
            other.getRootDelay())) return false;
    if (java.lang.Double.doubleToLongBits(getRootDispersion())
        != java.lang.Double.doubleToLongBits(
            other.getRootDispersion())) return false;
    if (java.lang.Double.doubleToLongBits(getReferenceTimestamp())
        != java.lang.Double.doubleToLongBits(
            other.getReferenceTimestamp())) return false;
    if (java.lang.Double.doubleToLongBits(getOriginateTimestamp())
        != java.lang.Double.doubleToLongBits(
            other.getOriginateTimestamp())) return false;
    if (java.lang.Double.doubleToLongBits(getReceiveTimestamp())
        != java.lang.Double.doubleToLongBits(
            other.getReceiveTimestamp())) return false;
    if (java.lang.Double.doubleToLongBits(getTransmitTimestamp())
        != java.lang.Double.doubleToLongBits(
            other.getTransmitTimestamp())) return false;
    if (getReferenceTimestampMsSince1970()
        != other.getReferenceTimestampMsSince1970()) return false;
    if (getOriginateTimestampMsSince1970()
        != other.getOriginateTimestampMsSince1970()) return false;
    if (getReceiveTimestampMsSince1970()
        != other.getReceiveTimestampMsSince1970()) return false;
    if (getTransmitTimestampMsSince1970()
        != other.getTransmitTimestampMsSince1970()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEAP_INDICATOR_FIELD_NUMBER;
    hash = (53 * hash) + getLeapIndicator();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + getMode();
    hash = (37 * hash) + STRATUM_FIELD_NUMBER;
    hash = (53 * hash) + getStratum();
    hash = (37 * hash) + POLL_INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getPollInterval();
    hash = (37 * hash) + PRECISION_FIELD_NUMBER;
    hash = (53 * hash) + getPrecision();
    hash = (37 * hash) + ROOT_DELAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRootDelay()));
    hash = (37 * hash) + ROOT_DISPERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRootDispersion()));
    hash = (37 * hash) + REFERENCE_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getReferenceTimestamp()));
    hash = (37 * hash) + ORIGINATE_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOriginateTimestamp()));
    hash = (37 * hash) + RECEIVE_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getReceiveTimestamp()));
    hash = (37 * hash) + TRANSMIT_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTransmitTimestamp()));
    hash = (37 * hash) + REFERENCE_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReferenceTimestampMsSince1970());
    hash = (37 * hash) + ORIGINATE_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOriginateTimestampMsSince1970());
    hash = (37 * hash) + RECEIVE_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReceiveTimestampMsSince1970());
    hash = (37 * hash) + TRANSMIT_TIMESTAMP_MS_SINCE_1970_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTransmitTimestampMsSince1970());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.igtimi.timesync.proto.NTPResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.igtimi.timesync.proto.NTPResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.igtimi.timesync.proto.NTPResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.igtimi.timesync.proto.NTPResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.igtimi.NTPResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.igtimi.NTPResponse)
      com.igtimi.timesync.proto.NTPResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_NTPResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_NTPResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.igtimi.timesync.proto.NTPResponse.class, com.igtimi.timesync.proto.NTPResponse.Builder.class);
    }

    // Construct using com.igtimi.timesync.proto.NTPResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      leapIndicator_ = 0;
      version_ = 0;
      mode_ = 0;
      stratum_ = 0;
      pollInterval_ = 0;
      precision_ = 0;
      rootDelay_ = 0D;
      rootDispersion_ = 0D;
      referenceTimestamp_ = 0D;
      originateTimestamp_ = 0D;
      receiveTimestamp_ = 0D;
      transmitTimestamp_ = 0D;
      referenceTimestampMsSince1970_ = 0L;
      originateTimestampMsSince1970_ = 0L;
      receiveTimestampMsSince1970_ = 0L;
      transmitTimestampMsSince1970_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_NTPResponse_descriptor;
    }

    @java.lang.Override
    public com.igtimi.timesync.proto.NTPResponse getDefaultInstanceForType() {
      return com.igtimi.timesync.proto.NTPResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.igtimi.timesync.proto.NTPResponse build() {
      com.igtimi.timesync.proto.NTPResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.igtimi.timesync.proto.NTPResponse buildPartial() {
      com.igtimi.timesync.proto.NTPResponse result = new com.igtimi.timesync.proto.NTPResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.igtimi.timesync.proto.NTPResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.leapIndicator_ = leapIndicator_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mode_ = mode_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.stratum_ = stratum_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.pollInterval_ = pollInterval_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.precision_ = precision_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.rootDelay_ = rootDelay_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.rootDispersion_ = rootDispersion_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.referenceTimestamp_ = referenceTimestamp_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.originateTimestamp_ = originateTimestamp_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.receiveTimestamp_ = receiveTimestamp_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.transmitTimestamp_ = transmitTimestamp_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.referenceTimestampMsSince1970_ = referenceTimestampMsSince1970_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.originateTimestampMsSince1970_ = originateTimestampMsSince1970_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.receiveTimestampMsSince1970_ = receiveTimestampMsSince1970_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.transmitTimestampMsSince1970_ = transmitTimestampMsSince1970_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.igtimi.timesync.proto.NTPResponse) {
        return mergeFrom((com.igtimi.timesync.proto.NTPResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.igtimi.timesync.proto.NTPResponse other) {
      if (other == com.igtimi.timesync.proto.NTPResponse.getDefaultInstance()) return this;
      if (other.getLeapIndicator() != 0) {
        setLeapIndicator(other.getLeapIndicator());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getMode() != 0) {
        setMode(other.getMode());
      }
      if (other.getStratum() != 0) {
        setStratum(other.getStratum());
      }
      if (other.getPollInterval() != 0) {
        setPollInterval(other.getPollInterval());
      }
      if (other.getPrecision() != 0) {
        setPrecision(other.getPrecision());
      }
      if (other.getRootDelay() != 0D) {
        setRootDelay(other.getRootDelay());
      }
      if (other.getRootDispersion() != 0D) {
        setRootDispersion(other.getRootDispersion());
      }
      if (other.getReferenceTimestamp() != 0D) {
        setReferenceTimestamp(other.getReferenceTimestamp());
      }
      if (other.getOriginateTimestamp() != 0D) {
        setOriginateTimestamp(other.getOriginateTimestamp());
      }
      if (other.getReceiveTimestamp() != 0D) {
        setReceiveTimestamp(other.getReceiveTimestamp());
      }
      if (other.getTransmitTimestamp() != 0D) {
        setTransmitTimestamp(other.getTransmitTimestamp());
      }
      if (other.getReferenceTimestampMsSince1970() != 0L) {
        setReferenceTimestampMsSince1970(other.getReferenceTimestampMsSince1970());
      }
      if (other.getOriginateTimestampMsSince1970() != 0L) {
        setOriginateTimestampMsSince1970(other.getOriginateTimestampMsSince1970());
      }
      if (other.getReceiveTimestampMsSince1970() != 0L) {
        setReceiveTimestampMsSince1970(other.getReceiveTimestampMsSince1970());
      }
      if (other.getTransmitTimestampMsSince1970() != 0L) {
        setTransmitTimestampMsSince1970(other.getTransmitTimestampMsSince1970());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              leapIndicator_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              version_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              mode_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              stratum_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              pollInterval_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              precision_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 57: {
              rootDelay_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 65: {
              rootDispersion_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 73: {
              referenceTimestamp_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            case 81: {
              originateTimestamp_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 89: {
              receiveTimestamp_ = input.readDouble();
              bitField0_ |= 0x00000400;
              break;
            } // case 89
            case 97: {
              transmitTimestamp_ = input.readDouble();
              bitField0_ |= 0x00000800;
              break;
            } // case 97
            case 104: {
              referenceTimestampMsSince1970_ = input.readUInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 112: {
              originateTimestampMsSince1970_ = input.readUInt64();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              receiveTimestampMsSince1970_ = input.readUInt64();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 128: {
              transmitTimestampMsSince1970_ = input.readUInt64();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int leapIndicator_ ;
    /**
     * <code>uint32 leap_indicator = 1 [json_name = "leapIndicator"];</code>
     * @return The leapIndicator.
     */
    @java.lang.Override
    public int getLeapIndicator() {
      return leapIndicator_;
    }
    /**
     * <code>uint32 leap_indicator = 1 [json_name = "leapIndicator"];</code>
     * @param value The leapIndicator to set.
     * @return This builder for chaining.
     */
    public Builder setLeapIndicator(int value) {

      leapIndicator_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 leap_indicator = 1 [json_name = "leapIndicator"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLeapIndicator() {
      bitField0_ = (bitField0_ & ~0x00000001);
      leapIndicator_ = 0;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>uint32 version = 2 [json_name = "version"];</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>uint32 version = 2 [json_name = "version"];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {

      version_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 version = 2 [json_name = "version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      version_ = 0;
      onChanged();
      return this;
    }

    private int mode_ ;
    /**
     * <code>uint32 mode = 3 [json_name = "mode"];</code>
     * @return The mode.
     */
    @java.lang.Override
    public int getMode() {
      return mode_;
    }
    /**
     * <code>uint32 mode = 3 [json_name = "mode"];</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(int value) {

      mode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 mode = 3 [json_name = "mode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mode_ = 0;
      onChanged();
      return this;
    }

    private int stratum_ ;
    /**
     * <code>uint32 stratum = 4 [json_name = "stratum"];</code>
     * @return The stratum.
     */
    @java.lang.Override
    public int getStratum() {
      return stratum_;
    }
    /**
     * <code>uint32 stratum = 4 [json_name = "stratum"];</code>
     * @param value The stratum to set.
     * @return This builder for chaining.
     */
    public Builder setStratum(int value) {

      stratum_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 stratum = 4 [json_name = "stratum"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStratum() {
      bitField0_ = (bitField0_ & ~0x00000008);
      stratum_ = 0;
      onChanged();
      return this;
    }

    private int pollInterval_ ;
    /**
     * <code>uint32 poll_interval = 5 [json_name = "pollInterval"];</code>
     * @return The pollInterval.
     */
    @java.lang.Override
    public int getPollInterval() {
      return pollInterval_;
    }
    /**
     * <code>uint32 poll_interval = 5 [json_name = "pollInterval"];</code>
     * @param value The pollInterval to set.
     * @return This builder for chaining.
     */
    public Builder setPollInterval(int value) {

      pollInterval_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 poll_interval = 5 [json_name = "pollInterval"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPollInterval() {
      bitField0_ = (bitField0_ & ~0x00000010);
      pollInterval_ = 0;
      onChanged();
      return this;
    }

    private int precision_ ;
    /**
     * <code>int32 precision = 6 [json_name = "precision"];</code>
     * @return The precision.
     */
    @java.lang.Override
    public int getPrecision() {
      return precision_;
    }
    /**
     * <code>int32 precision = 6 [json_name = "precision"];</code>
     * @param value The precision to set.
     * @return This builder for chaining.
     */
    public Builder setPrecision(int value) {

      precision_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 precision = 6 [json_name = "precision"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPrecision() {
      bitField0_ = (bitField0_ & ~0x00000020);
      precision_ = 0;
      onChanged();
      return this;
    }

    private double rootDelay_ ;
    /**
     * <code>double root_delay = 7 [json_name = "rootDelay"];</code>
     * @return The rootDelay.
     */
    @java.lang.Override
    public double getRootDelay() {
      return rootDelay_;
    }
    /**
     * <code>double root_delay = 7 [json_name = "rootDelay"];</code>
     * @param value The rootDelay to set.
     * @return This builder for chaining.
     */
    public Builder setRootDelay(double value) {

      rootDelay_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double root_delay = 7 [json_name = "rootDelay"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRootDelay() {
      bitField0_ = (bitField0_ & ~0x00000040);
      rootDelay_ = 0D;
      onChanged();
      return this;
    }

    private double rootDispersion_ ;
    /**
     * <code>double root_dispersion = 8 [json_name = "rootDispersion"];</code>
     * @return The rootDispersion.
     */
    @java.lang.Override
    public double getRootDispersion() {
      return rootDispersion_;
    }
    /**
     * <code>double root_dispersion = 8 [json_name = "rootDispersion"];</code>
     * @param value The rootDispersion to set.
     * @return This builder for chaining.
     */
    public Builder setRootDispersion(double value) {

      rootDispersion_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>double root_dispersion = 8 [json_name = "rootDispersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRootDispersion() {
      bitField0_ = (bitField0_ & ~0x00000080);
      rootDispersion_ = 0D;
      onChanged();
      return this;
    }

    private double referenceTimestamp_ ;
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double reference_timestamp = 9 [json_name = "referenceTimestamp"];</code>
     * @return The referenceTimestamp.
     */
    @java.lang.Override
    public double getReferenceTimestamp() {
      return referenceTimestamp_;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double reference_timestamp = 9 [json_name = "referenceTimestamp"];</code>
     * @param value The referenceTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceTimestamp(double value) {

      referenceTimestamp_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double reference_timestamp = 9 [json_name = "referenceTimestamp"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000100);
      referenceTimestamp_ = 0D;
      onChanged();
      return this;
    }

    private double originateTimestamp_ ;
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double originate_timestamp = 10 [json_name = "originateTimestamp"];</code>
     * @return The originateTimestamp.
     */
    @java.lang.Override
    public double getOriginateTimestamp() {
      return originateTimestamp_;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double originate_timestamp = 10 [json_name = "originateTimestamp"];</code>
     * @param value The originateTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setOriginateTimestamp(double value) {

      originateTimestamp_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double originate_timestamp = 10 [json_name = "originateTimestamp"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginateTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000200);
      originateTimestamp_ = 0D;
      onChanged();
      return this;
    }

    private double receiveTimestamp_ ;
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double receive_timestamp = 11 [json_name = "receiveTimestamp"];</code>
     * @return The receiveTimestamp.
     */
    @java.lang.Override
    public double getReceiveTimestamp() {
      return receiveTimestamp_;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double receive_timestamp = 11 [json_name = "receiveTimestamp"];</code>
     * @param value The receiveTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setReceiveTimestamp(double value) {

      receiveTimestamp_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double receive_timestamp = 11 [json_name = "receiveTimestamp"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiveTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000400);
      receiveTimestamp_ = 0D;
      onChanged();
      return this;
    }

    private double transmitTimestamp_ ;
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double transmit_timestamp = 12 [json_name = "transmitTimestamp"];</code>
     * @return The transmitTimestamp.
     */
    @java.lang.Override
    public double getTransmitTimestamp() {
      return transmitTimestamp_;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double transmit_timestamp = 12 [json_name = "transmitTimestamp"];</code>
     * @param value The transmitTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTransmitTimestamp(double value) {

      transmitTimestamp_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * in seconds since 1900
     * </pre>
     *
     * <code>double transmit_timestamp = 12 [json_name = "transmitTimestamp"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTransmitTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000800);
      transmitTimestamp_ = 0D;
      onChanged();
      return this;
    }

    private long referenceTimestampMsSince1970_ ;
    /**
     * <pre>
     * These fields are not part of the standard message
     * </pre>
     *
     * <code>uint64 reference_timestamp_ms_since_1970 = 13 [json_name = "referenceTimestampMs1970"];</code>
     * @return The referenceTimestampMsSince1970.
     */
    @java.lang.Override
    public long getReferenceTimestampMsSince1970() {
      return referenceTimestampMsSince1970_;
    }
    /**
     * <pre>
     * These fields are not part of the standard message
     * </pre>
     *
     * <code>uint64 reference_timestamp_ms_since_1970 = 13 [json_name = "referenceTimestampMs1970"];</code>
     * @param value The referenceTimestampMsSince1970 to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceTimestampMsSince1970(long value) {

      referenceTimestampMsSince1970_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * These fields are not part of the standard message
     * </pre>
     *
     * <code>uint64 reference_timestamp_ms_since_1970 = 13 [json_name = "referenceTimestampMs1970"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceTimestampMsSince1970() {
      bitField0_ = (bitField0_ & ~0x00001000);
      referenceTimestampMsSince1970_ = 0L;
      onChanged();
      return this;
    }

    private long originateTimestampMsSince1970_ ;
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 originate_timestamp_ms_since_1970 = 14 [json_name = "originateTimestampMs1970"];</code>
     * @return The originateTimestampMsSince1970.
     */
    @java.lang.Override
    public long getOriginateTimestampMsSince1970() {
      return originateTimestampMsSince1970_;
    }
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 originate_timestamp_ms_since_1970 = 14 [json_name = "originateTimestampMs1970"];</code>
     * @param value The originateTimestampMsSince1970 to set.
     * @return This builder for chaining.
     */
    public Builder setOriginateTimestampMsSince1970(long value) {

      originateTimestampMsSince1970_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 originate_timestamp_ms_since_1970 = 14 [json_name = "originateTimestampMs1970"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginateTimestampMsSince1970() {
      bitField0_ = (bitField0_ & ~0x00002000);
      originateTimestampMsSince1970_ = 0L;
      onChanged();
      return this;
    }

    private long receiveTimestampMsSince1970_ ;
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 receive_timestamp_ms_since_1970 = 15 [json_name = "receiveTimestampMs1970"];</code>
     * @return The receiveTimestampMsSince1970.
     */
    @java.lang.Override
    public long getReceiveTimestampMsSince1970() {
      return receiveTimestampMsSince1970_;
    }
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 receive_timestamp_ms_since_1970 = 15 [json_name = "receiveTimestampMs1970"];</code>
     * @param value The receiveTimestampMsSince1970 to set.
     * @return This builder for chaining.
     */
    public Builder setReceiveTimestampMsSince1970(long value) {

      receiveTimestampMsSince1970_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 receive_timestamp_ms_since_1970 = 15 [json_name = "receiveTimestampMs1970"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiveTimestampMsSince1970() {
      bitField0_ = (bitField0_ & ~0x00004000);
      receiveTimestampMsSince1970_ = 0L;
      onChanged();
      return this;
    }

    private long transmitTimestampMsSince1970_ ;
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 transmit_timestamp_ms_since_1970 = 16 [json_name = "transmitTimestampMs1970"];</code>
     * @return The transmitTimestampMsSince1970.
     */
    @java.lang.Override
    public long getTransmitTimestampMsSince1970() {
      return transmitTimestampMsSince1970_;
    }
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 transmit_timestamp_ms_since_1970 = 16 [json_name = "transmitTimestampMs1970"];</code>
     * @param value The transmitTimestampMsSince1970 to set.
     * @return This builder for chaining.
     */
    public Builder setTransmitTimestampMsSince1970(long value) {

      transmitTimestampMsSince1970_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * in ms since 1970
     * </pre>
     *
     * <code>uint64 transmit_timestamp_ms_since_1970 = 16 [json_name = "transmitTimestampMs1970"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTransmitTimestampMsSince1970() {
      bitField0_ = (bitField0_ & ~0x00008000);
      transmitTimestampMsSince1970_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.igtimi.NTPResponse)
  }

  // @@protoc_insertion_point(class_scope:com.igtimi.NTPResponse)
  private static final com.igtimi.timesync.proto.NTPResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.igtimi.timesync.proto.NTPResponse();
  }

  public static com.igtimi.timesync.proto.NTPResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NTPResponse>
      PARSER = new com.google.protobuf.AbstractParser<NTPResponse>() {
    @java.lang.Override
    public NTPResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NTPResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NTPResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.igtimi.timesync.proto.NTPResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

