// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/igtimi/IgtimiTimeSync.proto
// Protobuf Java Version: 4.28.3

package com.igtimi.timesync.proto;

public interface NTPResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.igtimi.NTPResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 leap_indicator = 1 [json_name = "leapIndicator"];</code>
   * @return The leapIndicator.
   */
  int getLeapIndicator();

  /**
   * <code>uint32 version = 2 [json_name = "version"];</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>uint32 mode = 3 [json_name = "mode"];</code>
   * @return The mode.
   */
  int getMode();

  /**
   * <code>uint32 stratum = 4 [json_name = "stratum"];</code>
   * @return The stratum.
   */
  int getStratum();

  /**
   * <code>uint32 poll_interval = 5 [json_name = "pollInterval"];</code>
   * @return The pollInterval.
   */
  int getPollInterval();

  /**
   * <code>int32 precision = 6 [json_name = "precision"];</code>
   * @return The precision.
   */
  int getPrecision();

  /**
   * <code>double root_delay = 7 [json_name = "rootDelay"];</code>
   * @return The rootDelay.
   */
  double getRootDelay();

  /**
   * <code>double root_dispersion = 8 [json_name = "rootDispersion"];</code>
   * @return The rootDispersion.
   */
  double getRootDispersion();

  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double reference_timestamp = 9 [json_name = "referenceTimestamp"];</code>
   * @return The referenceTimestamp.
   */
  double getReferenceTimestamp();

  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double originate_timestamp = 10 [json_name = "originateTimestamp"];</code>
   * @return The originateTimestamp.
   */
  double getOriginateTimestamp();

  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double receive_timestamp = 11 [json_name = "receiveTimestamp"];</code>
   * @return The receiveTimestamp.
   */
  double getReceiveTimestamp();

  /**
   * <pre>
   * in seconds since 1900
   * </pre>
   *
   * <code>double transmit_timestamp = 12 [json_name = "transmitTimestamp"];</code>
   * @return The transmitTimestamp.
   */
  double getTransmitTimestamp();

  /**
   * <pre>
   * These fields are not part of the standard message
   * </pre>
   *
   * <code>uint64 reference_timestamp_ms_since_1970 = 13 [json_name = "referenceTimestampMs1970"];</code>
   * @return The referenceTimestampMsSince1970.
   */
  long getReferenceTimestampMsSince1970();

  /**
   * <pre>
   * in ms since 1970
   * </pre>
   *
   * <code>uint64 originate_timestamp_ms_since_1970 = 14 [json_name = "originateTimestampMs1970"];</code>
   * @return The originateTimestampMsSince1970.
   */
  long getOriginateTimestampMsSince1970();

  /**
   * <pre>
   * in ms since 1970
   * </pre>
   *
   * <code>uint64 receive_timestamp_ms_since_1970 = 15 [json_name = "receiveTimestampMs1970"];</code>
   * @return The receiveTimestampMsSince1970.
   */
  long getReceiveTimestampMsSince1970();

  /**
   * <pre>
   * in ms since 1970
   * </pre>
   *
   * <code>uint64 transmit_timestamp_ms_since_1970 = 16 [json_name = "transmitTimestampMs1970"];</code>
   * @return The transmitTimestampMsSince1970.
   */
  long getTransmitTimestampMsSince1970();
}
