// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/igtimi/IgtimiTimeSync.proto
// Protobuf Java Version: 4.28.3

package com.igtimi.timesync.proto;

public interface SNTPRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.igtimi.SNTPRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
   * @return Whether the secondsSince1900 field is set.
   */
  boolean hasSecondsSince1900();
  /**
   * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
   * @return The secondsSince1900.
   */
  double getSecondsSince1900();

  /**
   * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
   * @return Whether the msSince1970 field is set.
   */
  boolean hasMsSince1970();
  /**
   * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
   * @return The msSince1970.
   */
  long getMsSince1970();

  com.igtimi.timesync.proto.SNTPRequest.SendTimestampCase getSendTimestampCase();
}
