// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/igtimi/IgtimiTimeSync.proto
// Protobuf Java Version: 4.28.3

package com.igtimi.timesync.proto;

/**
 * Protobuf type {@code com.igtimi.SNTPRequest}
 */
@SuppressWarnings({"unused", "unchecked"})
public final class SNTPRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.igtimi.SNTPRequest)
    SNTPRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      SNTPRequest.class.getName());
  }
  // Use SNTPRequest.newBuilder() to construct.
  private SNTPRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SNTPRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_SNTPRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_SNTPRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.igtimi.timesync.proto.SNTPRequest.class, com.igtimi.timesync.proto.SNTPRequest.Builder.class);
  }

  private int sendTimestampCase_ = 0;
  private java.lang.Object sendTimestamp_;
  public enum SendTimestampCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SECONDS_SINCE_1900(1),
    MS_SINCE_1970(2),
    SENDTIMESTAMP_NOT_SET(0);
    private final int value;
    private SendTimestampCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SendTimestampCase valueOf(int value) {
      return forNumber(value);
    }

    public static SendTimestampCase forNumber(int value) {
      switch (value) {
        case 1: return SECONDS_SINCE_1900;
        case 2: return MS_SINCE_1970;
        case 0: return SENDTIMESTAMP_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SendTimestampCase
  getSendTimestampCase() {
    return SendTimestampCase.forNumber(
        sendTimestampCase_);
  }

  public static final int SECONDS_SINCE_1900_FIELD_NUMBER = 1;
  /**
   * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
   * @return Whether the secondsSince1900 field is set.
   */
  @java.lang.Override
  public boolean hasSecondsSince1900() {
    return sendTimestampCase_ == 1;
  }
  /**
   * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
   * @return The secondsSince1900.
   */
  @java.lang.Override
  public double getSecondsSince1900() {
    if (sendTimestampCase_ == 1) {
      return (java.lang.Double) sendTimestamp_;
    }
    return 0D;
  }

  public static final int MS_SINCE_1970_FIELD_NUMBER = 2;
  /**
   * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
   * @return Whether the msSince1970 field is set.
   */
  @java.lang.Override
  public boolean hasMsSince1970() {
    return sendTimestampCase_ == 2;
  }
  /**
   * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
   * @return The msSince1970.
   */
  @java.lang.Override
  public long getMsSince1970() {
    if (sendTimestampCase_ == 2) {
      return (java.lang.Long) sendTimestamp_;
    }
    return 0L;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sendTimestampCase_ == 1) {
      output.writeDouble(
          1, (double)((java.lang.Double) sendTimestamp_));
    }
    if (sendTimestampCase_ == 2) {
      output.writeUInt64(
          2, (long)((java.lang.Long) sendTimestamp_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sendTimestampCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            1, (double)((java.lang.Double) sendTimestamp_));
    }
    if (sendTimestampCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            2, (long)((java.lang.Long) sendTimestamp_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.igtimi.timesync.proto.SNTPRequest)) {
      return super.equals(obj);
    }
    com.igtimi.timesync.proto.SNTPRequest other = (com.igtimi.timesync.proto.SNTPRequest) obj;

    if (!getSendTimestampCase().equals(other.getSendTimestampCase())) return false;
    switch (sendTimestampCase_) {
      case 1:
        if (java.lang.Double.doubleToLongBits(getSecondsSince1900())
            != java.lang.Double.doubleToLongBits(
                other.getSecondsSince1900())) return false;
        break;
      case 2:
        if (getMsSince1970()
            != other.getMsSince1970()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (sendTimestampCase_) {
      case 1:
        hash = (37 * hash) + SECONDS_SINCE_1900_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSecondsSince1900()));
        break;
      case 2:
        hash = (37 * hash) + MS_SINCE_1970_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMsSince1970());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.igtimi.timesync.proto.SNTPRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.igtimi.timesync.proto.SNTPRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.igtimi.timesync.proto.SNTPRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.igtimi.timesync.proto.SNTPRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.igtimi.SNTPRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.igtimi.SNTPRequest)
      com.igtimi.timesync.proto.SNTPRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_SNTPRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_SNTPRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.igtimi.timesync.proto.SNTPRequest.class, com.igtimi.timesync.proto.SNTPRequest.Builder.class);
    }

    // Construct using com.igtimi.timesync.proto.SNTPRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sendTimestampCase_ = 0;
      sendTimestamp_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.igtimi.timesync.proto.TimeSyncProto.internal_static_com_igtimi_SNTPRequest_descriptor;
    }

    @java.lang.Override
    public com.igtimi.timesync.proto.SNTPRequest getDefaultInstanceForType() {
      return com.igtimi.timesync.proto.SNTPRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.igtimi.timesync.proto.SNTPRequest build() {
      com.igtimi.timesync.proto.SNTPRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.igtimi.timesync.proto.SNTPRequest buildPartial() {
      com.igtimi.timesync.proto.SNTPRequest result = new com.igtimi.timesync.proto.SNTPRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.igtimi.timesync.proto.SNTPRequest result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.igtimi.timesync.proto.SNTPRequest result) {
      result.sendTimestampCase_ = sendTimestampCase_;
      result.sendTimestamp_ = this.sendTimestamp_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.igtimi.timesync.proto.SNTPRequest) {
        return mergeFrom((com.igtimi.timesync.proto.SNTPRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.igtimi.timesync.proto.SNTPRequest other) {
      if (other == com.igtimi.timesync.proto.SNTPRequest.getDefaultInstance()) return this;
      switch (other.getSendTimestampCase()) {
        case SECONDS_SINCE_1900: {
          setSecondsSince1900(other.getSecondsSince1900());
          break;
        }
        case MS_SINCE_1970: {
          setMsSince1970(other.getMsSince1970());
          break;
        }
        case SENDTIMESTAMP_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              sendTimestamp_ = input.readDouble();
              sendTimestampCase_ = 1;
              break;
            } // case 9
            case 16: {
              sendTimestamp_ = input.readUInt64();
              sendTimestampCase_ = 2;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int sendTimestampCase_ = 0;
    private java.lang.Object sendTimestamp_;
    public SendTimestampCase
        getSendTimestampCase() {
      return SendTimestampCase.forNumber(
          sendTimestampCase_);
    }

    public Builder clearSendTimestamp() {
      sendTimestampCase_ = 0;
      sendTimestamp_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
     * @return Whether the secondsSince1900 field is set.
     */
    public boolean hasSecondsSince1900() {
      return sendTimestampCase_ == 1;
    }
    /**
     * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
     * @return The secondsSince1900.
     */
    public double getSecondsSince1900() {
      if (sendTimestampCase_ == 1) {
        return (java.lang.Double) sendTimestamp_;
      }
      return 0D;
    }
    /**
     * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
     * @param value The secondsSince1900 to set.
     * @return This builder for chaining.
     */
    public Builder setSecondsSince1900(double value) {

      sendTimestampCase_ = 1;
      sendTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double seconds_since_1900 = 1 [json_name = "secondsSince1900"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSecondsSince1900() {
      if (sendTimestampCase_ == 1) {
        sendTimestampCase_ = 0;
        sendTimestamp_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
     * @return Whether the msSince1970 field is set.
     */
    public boolean hasMsSince1970() {
      return sendTimestampCase_ == 2;
    }
    /**
     * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
     * @return The msSince1970.
     */
    public long getMsSince1970() {
      if (sendTimestampCase_ == 2) {
        return (java.lang.Long) sendTimestamp_;
      }
      return 0L;
    }
    /**
     * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
     * @param value The msSince1970 to set.
     * @return This builder for chaining.
     */
    public Builder setMsSince1970(long value) {

      sendTimestampCase_ = 2;
      sendTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ms_since_1970 = 2 [json_name = "msSince1970"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMsSince1970() {
      if (sendTimestampCase_ == 2) {
        sendTimestampCase_ = 0;
        sendTimestamp_ = null;
        onChanged();
      }
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.igtimi.SNTPRequest)
  }

  // @@protoc_insertion_point(class_scope:com.igtimi.SNTPRequest)
  private static final com.igtimi.timesync.proto.SNTPRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.igtimi.timesync.proto.SNTPRequest();
  }

  public static com.igtimi.timesync.proto.SNTPRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SNTPRequest>
      PARSER = new com.google.protobuf.AbstractParser<SNTPRequest>() {
    @java.lang.Override
    public SNTPRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SNTPRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SNTPRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.igtimi.timesync.proto.SNTPRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

