// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/igtimi/IgtimiTimeSync.proto
// Protobuf Java Version: 4.28.3

package com.igtimi.timesync.proto;

public final class TimeSyncProto {
  private TimeSyncProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      TimeSyncProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_igtimi_SNTPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_igtimi_SNTPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_igtimi_NTPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_igtimi_NTPResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037com/igtimi/IgtimiTimeSync.proto\022\ncom.i" +
      "gtimi\"u\n\013SNTPRequest\022.\n\022seconds_since_19" +
      "00\030\001 \001(\001H\000R\020secondsSince1900\022$\n\rms_since" +
      "_1970\030\002 \001(\004H\000R\013msSince1970B\020\n\016send_times" +
      "tamp\"\323\005\n\013NTPResponse\022%\n\016leap_indicator\030\001" +
      " \001(\rR\rleapIndicator\022\030\n\007version\030\002 \001(\rR\007ve" +
      "rsion\022\022\n\004mode\030\003 \001(\rR\004mode\022\030\n\007stratum\030\004 \001" +
      "(\rR\007stratum\022#\n\rpoll_interval\030\005 \001(\rR\014poll" +
      "Interval\022\034\n\tprecision\030\006 \001(\005R\tprecision\022\035" +
      "\n\nroot_delay\030\007 \001(\001R\trootDelay\022\'\n\017root_di" +
      "spersion\030\010 \001(\001R\016rootDispersion\022/\n\023refere" +
      "nce_timestamp\030\t \001(\001R\022referenceTimestamp\022" +
      "/\n\023originate_timestamp\030\n \001(\001R\022originateT" +
      "imestamp\022+\n\021receive_timestamp\030\013 \001(\001R\020rec" +
      "eiveTimestamp\022-\n\022transmit_timestamp\030\014 \001(" +
      "\001R\021transmitTimestamp\022C\n!reference_timest" +
      "amp_ms_since_1970\030\r \001(\004R\030referenceTimest" +
      "ampMs1970\022C\n!originate_timestamp_ms_sinc" +
      "e_1970\030\016 \001(\004R\030originateTimestampMs1970\022?" +
      "\n\037receive_timestamp_ms_since_1970\030\017 \001(\004R" +
      "\026receiveTimestampMs1970\022A\n transmit_time" +
      "stamp_ms_since_1970\030\020 \001(\004R\027transmitTimes" +
      "tampMs19702N\n\014SNTPTimeSync\022>\n\010SyncTime\022\027" +
      ".com.igtimi.SNTPRequest\032\027.com.igtimi.NTP" +
      "Response\"\000B.\n\031com.igtimi.timesync.protoB" +
      "\rTimeSyncProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_igtimi_SNTPRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_igtimi_SNTPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_igtimi_SNTPRequest_descriptor,
        new java.lang.String[] { "SecondsSince1900", "MsSince1970", "SendTimestamp", });
    internal_static_com_igtimi_NTPResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_igtimi_NTPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_igtimi_NTPResponse_descriptor,
        new java.lang.String[] { "LeapIndicator", "Version", "Mode", "Stratum", "PollInterval", "Precision", "RootDelay", "RootDispersion", "ReferenceTimestamp", "OriginateTimestamp", "ReceiveTimestamp", "TransmitTimestamp", "ReferenceTimestampMsSince1970", "OriginateTimestampMsSince1970", "ReceiveTimestampMsSince1970", "TransmitTimestampMsSince1970", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
