//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 03:41:40 PM CET 
//


package com.sap.sailing.xrr.resultimport.schema;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRRaceResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRRaceResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="RaceID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NetPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="TeamPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RaceRank" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRRaceResult")
public class TRRaceResult {

    @XmlAttribute(name = "RaceID", required = true)
    protected String raceID;
    @XmlAttribute(name = "NetPoints", required = true)
    protected BigDecimal netPoints;
    @XmlAttribute(name = "TeamPoints", required = true)
    protected BigDecimal teamPoints;
    @XmlAttribute(name = "RaceRank")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger raceRank;

    /**
     * Gets the value of the raceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceID() {
        return raceID;
    }

    /**
     * Sets the value of the raceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceID(String value) {
        this.raceID = value;
    }

    /**
     * Gets the value of the netPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPoints() {
        return netPoints;
    }

    /**
     * Sets the value of the netPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPoints(BigDecimal value) {
        this.netPoints = value;
    }

    /**
     * Gets the value of the teamPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTeamPoints() {
        return teamPoints;
    }

    /**
     * Sets the value of the teamPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTeamPoints(BigDecimal value) {
        this.teamPoints = value;
    }

    /**
     * Gets the value of the raceRank property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRaceRank() {
        return raceRank;
    }

    /**
     * Sets the value of the raceRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRaceRank(BigInteger value) {
        this.raceRank = value;
    }

}
