#!/bin/bash
read -p "Secretname: " SECRETNAME
read -p "Docker username: " USERNAME
read -p "Password: " -s PASSWORD
read -p "
e-Mail: " EMAIL

kubectl create secret docker-registry $SECRETNAME --docker-server=https://index.docker.io/v1/ --docker-username=$USERNAME --docker-password=$PASSWORD --docker-email=$EMAIL

