#!/bin/bash
#
# mongodb   Starts sailing services like MongoDB
#
# chkconfig: 2345 95 10
# description: Sailing contains all sailing services

# Source function library.
. /etc/init.d/functions

RETVAL=0

MONGODB_BINARY=/opt/mongodb-linux-x86_64-1.8.1/bin/mongod
MONGODB_CONF_DIR=/etc/mongodb
MONGODB_START_INSTANCES="default dev live archive racecommittee_dev"

start_mongodb() {
    for conf in $MONGODB_START_INSTANCES; do
        echo "Starting MongoDB server $conf"
        rm -f /var/lib/mongodb/$conf/mongod.lock
        su - mongodb -c "$MONGODB_BINARY --quiet --fork -f $MONGODB_CONF_DIR/mongodb-$conf.cfg"
        RETVAL=$?
        [ $RETVAL -eq 0 ] && success || failure
    done

    # give database servers some time to start
    sleep 2
}

stop_mongodb() {
    killall mongod
    sleep 2
}

# See how we were called.
case "$1" in
  start)
    start_mongodb
        ;;
  stop)
    stop_mongodb
    ;;
  start-mongo)
    start_mongodb
    ;;
  start-wiki)
    start_wiki
    ;;
  status)
    status mongod
    RETVAL=$?
    ;;
  *)
        echo $"Usage: $0 {start|stop|status}"
        RETVAL=3
esac

exit $RETVAL
