CREATE COLUMN TABLE SAILING.EVENTS (
	id INTEGER PRIMARY KEY,
	name NVARCHAR(250) NOT NULL,
	startDate DATE NOT NULL,
	endDate DATE NOT NULL,
	venue NVARCHAR(250),
	listed BOOLEAN,
	description NVARCHAR(250)
);
CREATE ROW TABLE SAILING.SCORING_SCHEME (
	id NVARCHAR(20) PRIMARY KEY,
	description NVARCHAR(250)
);
CREATE ROW TABLE SAILING.RANKING_METRIC (
	id NVARCHAR(20) PRIMARY KEY,
	description NVARCHAR(250)
);
CREATE ROW TABLE SAILING.BOAT_CLASS (
	id NVARCHAR(20) PRIMARY KEY,
	description NVARCHAR(250),
	hullLengthInMeters DECIMAL(5, 2),
	hullBeamInMeters DECIMAL(4, 2),
	hullType NVARCHAR(20)
);
CREATE ROW TABLE SAILING.IRM (
        name NVARCHAR(4) PRIMARY KEY,
        discardable BOOLEAN,
        advanceCompetitorsTrackedWorse BOOLEAN,
        appliesAtStartOfRace BOOLEAN
);
CREATE COLUMN TABLE SAILING.REGATTAS (
	name NVARCHAR(20) PRIMARY KEY,
	boatClass NVARCHAR(20) NOT NULL,
	scoringSchema NVARCHAR(20) NOT NULL,
	rankingMetric NVARCHAR(20) NOT NULL,
	FOREIGN KEY (boatClass) REFERENCES SAILING.BOAT_CLASS (id),
	FOREIGN KEY (scoringSchema) REFERENCES SAILING.SCORING_SCHEME (id),
	FOREIGN KEY (rankingMetric) REFERENCES SAILING.RANKING_METRIC (id)
);
CREATE COLUMN TABLE SAILING.RACES (
	id NVARCHAR(20) PRIMARY KEY,
	name NVARCHAR(250) NOT NULL,
	regatta NVARCHAR(20) NOT NULL,
	raceColumn NVARCHAR(5) NOT NULL,
	fleet NVARCHAR(20) NOT NULL,
	boatClass NVARCHAR(20) NOT NULL,
	startOfTracking DATE NOT NULL,
	startOfRace DATE NOT NULL,
	endOfTracking DATE NOT NULL,
	endOfTrace DATE NOT NULL,
	avgWindSpeed DECIMAL(17, 3),
	WindSpeedUnit NVARCHAR(5) DEFAULT 'KTS',
	FOREIGN KEY (regatta) REFERENCES SAILING.REGATTAS (name),
	FOREIGN KEY (boatClass) REFERENCES SAILING.BOAT_CLASS (id)
);