#!/bin/bash
PRIMARY_MASTER=https://palma2024-master.sailing.omegatiming.com:9443
SECONDARY_MASTER=https://palma2024-secondary-master.sailing.omegatiming.com:9443
COMPARE_OUTPUT=$( /home/sailing/code/java/target/compareServers -ael ${SECONDARY_MASTER} ${PRIMARY_MASTER} )
if [ "$?" != "0" ]; then
  echo "Comparing ${SECONDARY_MASTER} with ${PRIMARY_MASTER} showed differences:

${COMPARE_OUTPUT}

Please consolidate, e.g., by doing a master data import or
by repeating the administrative operation you carried out on
the one side also on the other side." | notify-operators "DIFFERENCE BETWEEN PRIMARY AND SECONDARY MASTER"
fi
