package com.sap.sailing.shared.persistence.impl;

public enum FieldNames {
    // general:
    TIME_AS_MILLIS, KNOT_SPEED, DEGREE_BEARING, LAT_DEG, LNG_DEG,
    
    // DeviceIdentifer
    DEVICE_TYPE_SPECIFIC_ID, DEVICE_ID, DEVICE_TYPE, DEVICE_STRING_REPRESENTATION,

    // mark properties fields
    MARK_PROPERTIES_ID, MARK_PROPERTIES_FIXED_POSITION, MARK_PROPERTIES_TAGS, MARK_PROPERTIES_TRACKING_DEVICE_IDENTIFIER,
    MARK_PROPERTIES_TRACKING_DEVICE_LAST_POSITION_LNG, MARK_PROPERTIES_USED_ROLE, MARK_PROPERTIES_USED_TEMPLATE,
    // common mark properties
    COMMON_MARK_PROPERTIES_COLOR, COMMON_MARK_PROPERTIES_NAME, COMMON_MARK_PROPERTIES_PATTERN, COMMON_MARK_PROPERTIES_SHAPE, COMMON_MARK_PROPERTIES_SHORT_NAME, COMMON_MARK_PROPERTIES_TYPE,

    // mark template fields
    MARK_TEMPLATE_ID,
    
    // mark role fields
    MARK_ROLE_ID, MARK_ROLE_NAME,

    // repeatable part
    REPEATABLE_PART_START, REPEATABLE_PART_END,

    // course template fields
    COURSE_TEMPLATE_ID, COURSE_TEMPLATE_NAME, COURSE_TEMPLATE_IMAGE_URL, COURSE_TEMPLATE_MARK_TEMPLATES, COURSE_TEMPLATE_MARK_TEMPLATE_ID, COURSE_TEMPLATE_MARK_TEMPLATE_ROLE_ID, COURSE_TEMPLATE_TAGS, COURSE_TEMPLATE_REPEATABLE_PART, COURSE_TEMPLATE_WAYPOINTS, COURSE_TEMPLATE_DEFAULT_NUMBER_OF_LAPS,

    // waypoint template fields
    WAYPOINT_TEMPLATE_PASSINGINSTRUCTION, WAYPOINT_TEMPLATE_MARK_TEMPLATES, WAYPOINT_TEMPLATE_CONTROL_POINT_NAME, WAYPOINT_TEMPLATE_CONTROL_POINT_SHORT_NAME
}
