package com.sap.sse.gwt.shared;

import com.google.gwt.core.client.GWT;
import com.sap.sse.gwt.client.context.data.SapSailingContextDataJSO;
import com.sap.sse.gwt.client.context.impl.SapSailingContextDataFactoryImpl;

/**
 * Provides information for the GWT client if debranding/whitelabeling is currently active.
 * Data is read from the static HTML page which starts the GWT client code.
 * Within the header there is  script section that contains such a structure:
 * <pre>
 *      document.sailingContext = &lbrace;
 *          debrandingActive: true&rbrace;;
 * </pre>
 * The data in this structure is integrated into the document object tree within the browser.
 * That can be accessed from here using the {@link SapSailingContextDataJSO}.
 * 
 * The structure in the HTML is generated by the server see ClientConfigurationServlet for that.
 * 
 * To add new fields the following steps must be performed:
 * <ul>
 * <li>template within the HTML page must be extend by a new field declaration inside {@code document.sailingContext}.</li>
 * <li>corresponding variable must be declared and filled with the appropriate value in {@link ClientConfigurationServlet}</li>
 * <li>class {@link SapSailingContextDataJSO} must be extended with an getter for the new field</li>
 * </ul>
 * 
 * @author Georg Herdt
 *
 */
public class Branding {

    private static final Branding INSTANCE;

    static {
        INSTANCE = new Branding();
    }

    public static Branding getInstance() {
        return INSTANCE;
    }

    private boolean active = true;

    public Branding() {
        try {
            SapSailingContextDataJSO dataJso = new SapSailingContextDataFactoryImpl().getInstance();
            active = !dataJso.isDebrandingActive();
        } catch (RuntimeException e) {
            GWT.log("no debranding information found.");
        }
    }

    /**
     * Access whitelabeling information.
     * @return true when branding information shall be shown
     */
    public boolean isActive() {
        return active;
    }
}
