package com.sap.sse.gwt.shared;

import com.google.gwt.core.client.GWT;
import com.sap.sse.gwt.client.context.data.ClientConfigurationContextDataJSO;
import com.sap.sse.gwt.client.context.impl.ClientConfigurationContextDataFactoryImpl;

/**
 * Provides information for the GWT client if debranding/whitelabeling is currently brandingActive.
 * Data is read from the static HTML page which starts the GWT client code.
 * Within the header there is  script section that contains such a structure:
 * <pre>
 *      document.clientConfigurationContext = &lbrace;
 *          debrandingActive: true&rbrace;;
 * </pre>
 * The data in this structure is integrated into the document object tree within the browser.
 * That can be accessed from here using the {@link ClientConfigurationContextDataJSO}.
 * 
 * The structure in the HTML is generated by the server see ClientConfigurationFilter for that.
 * 
 * To add new fields the following steps must be performed:
 * <ul>
 * <li>template within the HTML page must be extend by a new field declaration inside {@code document.clientConfigurationContext}.</li>
 * <li>corresponding variable must be declared and filled with the appropriate value in {@link ClientConfigurationFilter}</li>
 * <li>class {@link ClientConfigurationContextDataJSO} must be extended with an getter for the new field</li>
 * </ul>
 * 
 * @author Georg Herdt
 *
 */
public class ClientConfiguration {

    private static final ClientConfiguration INSTANCE;

    static {
        INSTANCE = new ClientConfiguration();
    }

    public static ClientConfiguration getInstance() {
        return INSTANCE;
    }

    private boolean brandingActive = true;

    public ClientConfiguration() {
        try {
            ClientConfigurationContextDataJSO dataJso = new ClientConfigurationContextDataFactoryImpl().getInstance();
            brandingActive = !dataJso.isDebrandingActive();
        } catch (RuntimeException e) {
            GWT.log("no debranding information found.");
        }
    }

    /**
     * Access whitelabeling information.
     * @return true when branding information shall be shown
     */
    public boolean isBrandingActive() {
        return brandingActive;
    }
}
