#!/bin/bash

# Use like this:
#
#    echo "MY_SECRET_ENV_VAR=\\\"some secret that may even contain blanks or = or &\\\"" | ./addSecret
#
# Copy stdin to SECRETS_TO_ADD
SECRETS_TO_ADD=$( cat )
SERVERS_PATH=/home/sailing/servers
SECRETS_PATH=/root/secrets
SECRETS_IN_APP_PATH=configuration/secrets
FIND_ANALYTICS_SERVERS_SCRIPT="$( dirname ${0} )/findSailingAnalyticsServers"
for IP in $( ${FIND_ANALYTICS_SERVERS_SCRIPT} ); do
  echo "Handling server with IP ${IP} ..."
  ssh root@$IP 'echo "Appending '${SECRETS_TO_ADD}' to '${SECRETS_PATH}'"
echo "'${SECRETS_TO_ADD}'" >>'${SECRETS_PATH}'
echo "Server directories:"
for i in $( ls '${SERVERS_PATH}' ); do
  echo "Appending to '${SERVERS_PATH}'/${i}/'${SECRETS_IN_APP_PATH}'"
  echo "'${SECRETS_TO_ADD}'" >>'${SERVERS_PATH}'/${i}/'${SECRETS_IN_APP_PATH}'
done'
done
