#!/bin/bash
# Example usage:
#   ./downloadTracTracEvent https://event.tractrac.com/events/event_20150625_KielerWoch/jsonservice.php /tmp/KielerWoche2015
#
# To obtain the set of TracTrac JSON URLs currently in use by the archive, on
# dbserver.internal.sapsailing.com try this:
#   mongo --quiet "mongodb://dbserver.internal.sapsailing.com:10201/winddb?replicaSet=archive" --eval 'db.TRACTRAC_CONFIGURATIONS.find({}, {TT_CONFIG_JSON_URL : 1}).toArray()' | grep -v ObjectId | jq -r '.[].TT_CONFIG_JSON_URL' | sort -u >/tmp/tractrac-json-urls
# and then:
#   for i in `cat /tmp/tractrac-json-urls`; do ./downloadTracTracEvent $i /tmp/tractrac-tracks; done
# and you will get a folder per event under /tmp/tractrac-tracks with all .mtb and .txt files as well
# as the .json file in them.
EVENT_JSON_URL="${1}"
EVENT_DB="$( basename $( dirname ${EVENT_JSON_URL} ) )"
TARGET_DIR="${2}/${EVENT_DB}"
if [ ! -d "${TARGET_DIR}" ]; then
  echo "${TARGET_DIR} does not exist; making it..."
  mkdir -p "${TARGET_DIR}"
fi
pushd "${TARGET_DIR}"
for params_url in `wget -O - "${EVENT_JSON_URL}" | tee "${EVENT_DB}.json" | jq -r '.races[].params_url'`; do
  echo ${params_url}
  wget "${params_url}"
  FILE="`basename ${params_url}`"
  STORED_URI_PART=`grep -i ^stored-uri: "${FILE}" | head -1 | sed -e 's/^stored-uri://'`
  STORED_URI="`dirname ${EVENT_JSON_URL}`/${STORED_URI_PART}"
  echo "stored-uri: ${STORED_URI}"
  wget "${STORED_URI}"
done
popd
