#!/bin/sh
# Counts the lines per committer currently in the tree, for all files with type
# .java, .MF, .properties, .swift and .xml
git ls-tree -r --name-only HEAD -- | grep "\(\.java$\)\|\(\.MF$\)\|\(\.properties$\)\|\(\.swift$\)\|\(\.xml$\)" | xargs -n1 git blame HEAD | sed -e 's/^[^   ]* (\(.*\) [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].*$/\1/' | sort | uniq -c | sort -rn
