#!/bin/sh
# Counts the lines per committer currently in the tree, for all files with type
# .java, .MF, .properties, .swift and .xml
git ls-tree -r --name-only HEAD -- | grep "\(\.java$\)\|\(\.MF$\)\|\(\.properties$\)\|\(\.swift$\)\|\(\.xml$\)" | xargs -n1 git blame --line-porcelain HEAD | grep "^author " | sort | uniq -c | sort -nr
