#!/bin/bash


TAG="TESTPROXY"
DIR="/etc/httpd"
COMMAND="sudo service httpd reload"
MAIN_NAME="main"
while read oldrev newrev refname; do
    # Check if the update is on a branch
    if [[ $refname == "refs/heads/"* ]]; then
        branch_name=$(echo $refname | sed "s|refs/heads/\(.*\)$|\1|")
        echo "Update on branch: $branch_name"
        if [[ "$branch_name" == "$MAIN_NAME" ]]; then
                touch "/home/httpdConf/repo.git/hooks/notify"
        fi
    fi
done
