package com.sap.sailing.domain.common;

public enum ScoringSchemeType {
    LOW_POINT, HIGH_POINT, HIGH_POINT_ESS_OVERALL, HIGH_POINT_LAST_BREAKS_TIE, HIGH_POINT_FIRST_GETS_TEN,
    HIGH_POINT_FIRST_GETS_ONE, LOW_POINT_WINNER_GETS_ZERO, HIGH_POINT_WINNER_GETS_SIX, HIGH_POINT_WINNER_GETS_FIVE,
    HIGH_POINT_FIRST_GETS_TEN_OR_EIGHT,
    HIGH_POINT_WINNER_GETS_FIVE_IGNORING_RACE_COUNT,
    HIGH_POINT_WINNER_GETS_SIX_IGNORING_RACE_COUNT
}
