package com.sap.sse.security.persistence.impl;

public enum FieldNames {
    CACHE_NAME,
    
    SESSION_ID, SESSION_HOST, SESSION_LAST_ACCESS_TIME, SESSION_START_TIMESTAMP, SESSION_TIMEOUT,
    SESSION_ATTRIBUTES, SESSION_ATTRIBUTE_NAME, SESSION_ATTRIBUTE_VALUE, SESSION_PRINCIPAL_REALM_NAME,
    SESSION_PRINCIPAL_REALM_VALUE;
}
